In [1]:
import pandas as pd

In [2]:
data = {
    'Name': ['Ram', 'Ravi', 'Amit', 'Ram', 'Ravi'],
    'Dept': ['IT', 'HR', 'IT', 'HR', 'IT'],
    'Salary': [30000, 25000, 40000, 32000, 28000]
}

df = pd.DataFrame(data)

In [3]:
df

   Name Dept  Salary
0   Ram   IT   30000
1  Ravi   HR   25000
2  Amit   IT   40000
3   Ram   HR   32000
4  Ravi   IT   28000

In [4]:
df["Dept"].value_counts()  # frequency of values in month column

Dept
IT    3
HR    2
Name: count, dtype: int64

In [5]:
df[df["Dept"] == "IT"].value_counts()  #  frequency of values in month column where month =1

Name  Dept  Salary
Ram   IT    30000     1
Amit  IT    40000     1
Ravi  IT    28000     1
Name: count, dtype: int64

In [6]:
df.groupby("Dept")["Salary"].mean()  # dept wise avg salary

Dept
HR    28500.000000
IT    32666.666667
Name: Salary, dtype: float64

In [8]:
df.groupby("Dept")["Name"].count() # count of employees per department

Dept
HR    2
IT    3
Name: Name, dtype: int64

In [9]:
df.groupby("Dept")["Salary"].agg(["sum", "mean", "min", "max"])  # multiple aggregations

        sum          mean    min    max
Dept
HR    57000  28500.000000  25000  32000
IT    98000  32666.666667  28000  40000

In [10]:
# multiple columns group by department + Name combination wise result 
df.groupby(["Dept", "Name"])["Salary"].sum()

Dept  Name
HR    Ram     32000
      Ravi    25000
IT    Amit    40000
      Ram     30000
      Ravi    28000
Name: Salary, dtype: int64

In [11]:
# Named aggeragation (Advanced)
df.groupby("Dept").agg(
    total_salary = ("Salary", "sum"),
    avg_salary = ("Salary" , "mean"),
    count_Salary = ("Salary", "count")
)

      total_salary    avg_salary  count_Salary
Dept
HR           57000  28500.000000             2
IT           98000  32666.666667             3