In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.3'

In [3]:
# series are one dimension array
i = ["A","B","C","D","E"]
s = pd.Series([10,20,30,40,50],index = i)
print(s)

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [4]:
data = {
    "Product" : ["Laptop", "Smartphone", "Tablet"],
    "Price" : [40000, 34000, 50000],
    "Quantity" : [2,1,3]
}
df = pd.DataFrame(data , index = ["a","b","c"])
df

      Product  Price  Quantity
a      Laptop  40000         2
b  Smartphone  34000         1
c      Tablet  50000         3

In [5]:
df.loc['a',"Price"]

np.int64(40000)

In [6]:
df.iloc[0, 1]

np.int64(40000)

In [7]:
# read csv data
df = pd.read_csv("Pn_data.csv")

In [8]:
# read excel data
df = pd.read_excel("Sales_Dashboard_Data_1000_Rows_20_Columns.xlsx")

In [9]:
#  save file in csv
# df.to_csv("Sales.csv",index = False)

In [10]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
0,10001,2025-12-27,2271,Customer_2271,Female,52,Gwalior,MP,North,P662,Clothing,Jeans,1,40160,5,38152.00,28112.0,10040.00,Card,Rahul
1,10002,2025-08-12,2194,Customer_2194,Male,53,Indore,MP,West,P566,Furniture,Table,1,29341,5,27873.95,20538.7,7335.25,Cash,Neha
2,10003,2025-05-08,2135,Customer_2135,Male,27,Lucknow,UP,North,P966,Electronics,Laptop,3,38968,15,99368.40,81832.8,17535.60,UPI,Amit
3,10004,2025-07-18,2137,Customer_2137,Male,27,Indore,MP,West,P754,Furniture,Table,10,29099,10,261891.00,203693.0,58198.00,Card,Neha
4,10005,2025-04-29,2071,Customer_2071,Male,31,Gwalior,MP,North,P467,Clothing,Jeans,3,27041,15,68954.55,56786.1,12168.45,UPI,Karan

In [11]:
df.tail(1)

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
999,11000,2025-01-02,2058,Customer_2058,Male,45,Indore,MP,West,P478,Electronics,Laptop,5,17572,20,70288.0,61502.0,8786.0,UPI,Neha

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       1000 non-null   int64
 1   OrderDate     1000 non-null   str
 2   CustomerID    1000 non-null   int64
 3   CustomerName  1000 non-null   str
 4   Gender        1000 non-null   str
 5   Age           1000 non-null   int64
 6   City          1000 non-null   str
 7   State         1000 non-null   str
 8   Region        1000 non-null   str
 9   ProductID     1000 non-null   str
 10  Category      1000 non-null   str
 11  Product       1000 non-null   str
 12  Quantity      1000 non-null   int64
 13  UnitPrice     1000 non-null   int64
 14  DiscountPct   1000 non-null   int64
 15  Sales         1000 non-null   float64
 16  Cost          1000 non-null   float64
 17  Profit        1000 non-null   float64
 18  PaymentMode   1000 non-null   str
 19  SalesPerson   1000 non-null   str
dtypes: float64(3), int64(6), str(11)
memory usage: 156.4 KB

In [13]:
df.describe()

,OrderID,CustomerID,Age,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.00000,1000.000000
mean,10500.500000,2153.785000,39.865000,5.497000,24550.340000,9.975000,122208.04210,94943.54450,27264.497600
std,288.819436,84.431436,12.025864,2.851337,14049.555203,7.157206,102977.72842,79273.64029,26203.048859
min,10001.000000,2001.000000,18.000000,1.000000,204.000000,0.000000,603.90000,469.70000,118.000000
25%,10250.750000,2080.000000,30.000000,3.000000,12774.250000,5.000000,37346.92500,29545.42500,7716.350000
50%,10500.500000,2153.000000,40.000000,6.000000,24060.500000,10.000000,91228.00000,70361.20000,18420.025000
75%,10750.250000,2226.000000,50.000000,8.000000,36617.000000,15.000000,184651.60000,146273.40000,39147.600000
max,11000.000000,2300.000000,60.000000,10.000000,49954.000000,20.000000,482380.00000,341187.00000,144714.000000

In [14]:
df.shape

(1000, 20)

In [15]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
0,10001,2025-12-27,2271,Customer_2271,Female,52,Gwalior,MP,North,P662,Clothing,Jeans,1,40160,5,38152.00,28112.0,10040.00,Card,Rahul
1,10002,2025-08-12,2194,Customer_2194,Male,53,Indore,MP,West,P566,Furniture,Table,1,29341,5,27873.95,20538.7,7335.25,Cash,Neha
2,10003,2025-05-08,2135,Customer_2135,Male,27,Lucknow,UP,North,P966,Electronics,Laptop,3,38968,15,99368.40,81832.8,17535.60,UPI,Amit
3,10004,2025-07-18,2137,Customer_2137,Male,27,Indore,MP,West,P754,Furniture,Table,10,29099,10,261891.00,203693.0,58198.00,Card,Neha
4,10005,2025-04-29,2071,Customer_2071,Male,31,Gwalior,MP,North,P467,Clothing,Jeans,3,27041,15,68954.55,56786.1,12168.45,UPI,Karan

In [16]:
# df.loc[0,"City"]

In [17]:
# df.iloc[0,7]

In [18]:
df["Age"] # clomn selecttion

0      52
1      53
2      27
3      27
4      31
       ..
995    48
996    40
997    32
998    39
999    45
Name: Age, Length: 1000, dtype: int64

In [19]:
df[["Age","City","Product"]]

     Age     City   Product
0     52  Gwalior     Jeans
1     53   Indore     Table
2     27  Lucknow    Laptop
3     27   Indore     Table
4     31  Gwalior     Jeans
..   ...      ...       ...
995   48    Delhi    Jacket
996   40   Mumbai  Keyboard
997   32   Indore    Laptop
998   39   Mumbai     Sugar
999   45   Indore    Laptop

[1000 rows x 3 columns]

In [20]:
df[df["Sales"] > 290000] # filtering data

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
26,10027,2025-06-11,2108,Customer_2108,Male,56,Indore,MP,West,P217,Furniture,Desk,9,44497,5,380449.35,280331.1,100118.25,Net Banking,Priya
63,10064,2025-07-16,2093,Customer_2093,Female,43,Lucknow,UP,North,P320,Clothing,Jeans,10,47841,20,382728.00,334887.0,47841.00,Cash,Simran
73,10074,2025-10-13,2197,Customer_2197,Male,54,Gwalior,MP,North,P132,Clothing,Jacket,9,38718,15,296192.70,243923.4,52269.30,UPI,Simran
74,10075,2025-09-14,2158,Customer_2158,Female,58,Gwalior,MP,North,P121,Electronics,Laptop,10,42769,10,384921.00,299383.0,85538.00,Net Banking,Priya
77,10078,2025-01-12,2111,Customer_2111,Female,27,Delhi,Delhi,North,P612,Furniture,Desk,9,47509,0,427581.00,299306.7,128274.30,UPI,Priya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,10932,2025-06-09,2292,Customer_2292,Male,26,Gwalior,MP,North,P993,Grocery,Oil,10,47512,15,403852.00,332584.0,71268.00,Card,Karan
940,10941,2025-10-06,2019,Customer_2019,Male,38,Delhi,Delhi,North,P763,Electronics,Mouse,10,40856,5,388132.00,285992.0,102140.00,Cash,Neha
950,10951,2025-04-27,2104,Customer_2104,Male,58,Indore,MP,West,P934,Clothing,Shirt,8,49851,10,358927.20,279165.6,79761.60,UPI,Priya
959,10960,2025-12-18,2148,Customer_2148,Female,21,Jaipur,RJ,North,P471,Furniture,Table,8,49676,10,357667.20,278185.6,79481.60,Card,Neha
998,10999,2025-02-09,2220,Customer_2220,Female,39,Mumbai,MH,West,P602,Grocery,Sugar,8,48968,0,391744.00,274220.8,117523.20,UPI,Amit

In [21]:
df[df["City"] == "Indore"]

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
1,10002,2025-08-12,2194,Customer_2194,Male,53,Indore,MP,West,P566,Furniture,Table,1,29341,5,27873.95,20538.7,7335.25,Cash,Neha
3,10004,2025-07-18,2137,Customer_2137,Male,27,Indore,MP,West,P754,Furniture,Table,10,29099,10,261891.00,203693.0,58198.00,Card,Neha
5,10006,2025-02-24,2136,Customer_2136,Female,51,Indore,MP,West,P557,Grocery,Sugar,6,18672,0,112032.00,78422.4,33609.60,Net Banking,Priya
9,10010,2025-05-27,2151,Customer_2151,Male,44,Indore,MP,West,P938,Furniture,Table,1,44916,10,40424.40,31441.2,8983.20,Card,Amit
20,10021,2025-09-23,2242,Customer_2242,Female,41,Indore,MP,West,P651,Clothing,Jacket,8,6816,20,43622.40,38169.6,5452.80,Card,Priya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,10989,2025-11-03,2149,Customer_2149,Male,49,Indore,MP,West,P726,Electronics,Keyboard,6,49291,15,251384.10,207022.2,44361.90,Cash,Karan
991,10992,2025-09-07,2042,Customer_2042,Female,52,Indore,MP,West,P136,Electronics,Mouse,1,21493,5,20418.35,15045.1,5373.25,Cash,Rahul
993,10994,2025-11-07,2270,Customer_2270,Male,36,Indore,MP,West,P344,Furniture,Desk,2,49864,15,84768.80,69809.6,14959.20,Card,Neha
997,10998,2025-09-12,2217,Customer_2217,Male,32,Indore,MP,West,P223,Electronics,Laptop,2,39774,0,79548.00,55683.6,23864.40,Net Banking,Priya
999,11000,2025-01-02,2058,Customer_2058,Male,45,Indore,MP,West,P478,Electronics,Laptop,5,17572,20,70288.00,61502.0,8786.00,UPI,Neha

In [22]:
df.sort_values("Sales", inplace = False)

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
347,10348,2025-02-12,2096,Customer_2096,Female,58,Jaipur,RJ,North,P394,Furniture,Table,1,671,10,603.9,469.7,134.2,Net Banking,Priya
286,10287,2025-06-29,2002,Customer_2002,Male,22,Mumbai,MH,West,P671,Clothing,Jeans,1,1180,20,944.0,826.0,118.0,Cash,Priya
126,10127,2025-04-12,2029,Customer_2029,Male,26,Delhi,Delhi,North,P856,Clothing,Jacket,6,204,5,1162.8,856.8,306.0,UPI,Amit
455,10456,2025-01-11,2271,Customer_2271,Female,23,Lucknow,UP,North,P221,Grocery,Oil,4,339,5,1288.2,949.2,339.0,Net Banking,Rahul
653,10654,2025-03-06,2053,Customer_2053,Female,21,Mumbai,MH,West,P903,Furniture,Table,4,433,15,1472.2,1212.4,259.8,Cash,Priya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
758,10759,2025-05-17,2107,Customer_2107,Female,18,Mumbai,MH,West,P155,Electronics,Laptop,10,48741,10,438669.0,341187.0,97482.0,UPI,Priya
340,10341,2025-12-12,2190,Customer_2190,Male,34,Jaipur,RJ,North,P450,Electronics,Keyboard,9,49714,0,447426.0,313198.2,134227.8,Net Banking,Karan
282,10283,2025-04-03,2203,Customer_2203,Female,24,Delhi,Delhi,North,P203,Grocery,Sugar,10,47140,5,447830.0,329980.0,117850.0,Net Banking,Amit
745,10746,2025-09-16,2152,Customer_2152,Female,58,Indore,MP,West,P917,Clothing,Shirt,10,46169,0,461690.0,323183.0,138507.0,Net Banking,Amit
665,10666,2025-10-02,2257,Customer_2257,Female,56,Delhi,Delhi,North,P835,Grocery,Rice,10,48238,0,482380.0,337666.0,144714.0,Net Banking,Amit

In [23]:
df.head(3)

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
0,10001,2025-12-27,2271,Customer_2271,Female,52,Gwalior,MP,North,P662,Clothing,Jeans,1,40160,5,38152.00,28112.0,10040.00,Card,Rahul
1,10002,2025-08-12,2194,Customer_2194,Male,53,Indore,MP,West,P566,Furniture,Table,1,29341,5,27873.95,20538.7,7335.25,Cash,Neha
2,10003,2025-05-08,2135,Customer_2135,Male,27,Lucknow,UP,North,P966,Electronics,Laptop,3,38968,15,99368.40,81832.8,17535.60,UPI,Amit

In [24]:
df.tail()

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
995,10996,2025-08-21,2062,Customer_2062,Female,48,Delhi,Delhi,North,P746,Clothing,Jacket,6,2759,20,13243.2,11587.8,1655.4,Card,Amit
996,10997,2025-05-21,2034,Customer_2034,Female,40,Mumbai,MH,West,P956,Electronics,Keyboard,7,39196,10,246934.8,192060.4,54874.4,Net Banking,Priya
997,10998,2025-09-12,2217,Customer_2217,Male,32,Indore,MP,West,P223,Electronics,Laptop,2,39774,0,79548.0,55683.6,23864.4,Net Banking,Priya
998,10999,2025-02-09,2220,Customer_2220,Female,39,Mumbai,MH,West,P602,Grocery,Sugar,8,48968,0,391744.0,274220.8,117523.2,UPI,Amit
999,11000,2025-01-02,2058,Customer_2058,Male,45,Indore,MP,West,P478,Electronics,Laptop,5,17572,20,70288.0,61502.0,8786.0,UPI,Neha

In [29]:
df.sort_values(by = "Quantity")

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
0,10001,2025-12-27,2271,Customer_2271,Female,52,Gwalior,MP,North,P662,Clothing,Jeans,1,40160,5,38152.00,28112.0,10040.00,Card,Rahul
1,10002,2025-08-12,2194,Customer_2194,Male,53,Indore,MP,West,P566,Furniture,Table,1,29341,5,27873.95,20538.7,7335.25,Cash,Neha
969,10970,2025-12-31,2143,Customer_2143,Male,37,Gwalior,MP,North,P560,Clothing,Shirt,1,10266,5,9752.70,7186.2,2566.50,Cash,Rahul
970,10971,2025-06-04,2075,Customer_2075,Female,46,Indore,MP,West,P149,Furniture,Desk,1,44534,0,44534.00,31173.8,13360.20,Cash,Karan
972,10973,2025-05-20,2190,Customer_2190,Female,24,Delhi,Delhi,North,P230,Grocery,Rice,1,38393,20,30714.40,26875.1,3839.30,Card,Simran
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,10967,2025-11-11,2097,Customer_2097,Female,49,Delhi,Delhi,North,P254,Grocery,Rice,10,29291,15,248973.50,205037.0,43936.50,UPI,Priya
74,10075,2025-09-14,2158,Customer_2158,Female,58,Gwalior,MP,North,P121,Electronics,Laptop,10,42769,10,384921.00,299383.0,85538.00,Net Banking,Priya
75,10076,2025-04-10,2020,Customer_2020,Female,59,Indore,MP,West,P643,Clothing,Jeans,10,5183,0,51830.00,36281.0,15549.00,Card,Rahul
564,10565,2025-07-20,2284,Customer_2284,Male,56,Indore,MP,West,P903,Grocery,Sugar,10,34028,0,340280.00,238196.0,102084.00,Net Banking,Amit
609,10610,2025-08-14,2223,Customer_2223,Female,45,Delhi,Delhi,North,P373,Furniture,Chair,10,4197,20,33576.00,29379.0,4197.00,Card,Simran

In [33]:
df.set_index("CustomerID", inplace = False)

,OrderID,OrderDate,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
CustomerID,,,,,,,,,,,,,,,,,,,
2271,10001,2025-12-27,Customer_2271,Female,52,Gwalior,MP,North,P662,Clothing,Jeans,1,40160,5,38152.00,28112.0,10040.00,Card,Rahul
2194,10002,2025-08-12,Customer_2194,Male,53,Indore,MP,West,P566,Furniture,Table,1,29341,5,27873.95,20538.7,7335.25,Cash,Neha
2135,10003,2025-05-08,Customer_2135,Male,27,Lucknow,UP,North,P966,Electronics,Laptop,3,38968,15,99368.40,81832.8,17535.60,UPI,Amit
2137,10004,2025-07-18,Customer_2137,Male,27,Indore,MP,West,P754,Furniture,Table,10,29099,10,261891.00,203693.0,58198.00,Card,Neha
2071,10005,2025-04-29,Customer_2071,Male,31,Gwalior,MP,North,P467,Clothing,Jeans,3,27041,15,68954.55,56786.1,12168.45,UPI,Karan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2062,10996,2025-08-21,Customer_2062,Female,48,Delhi,Delhi,North,P746,Clothing,Jacket,6,2759,20,13243.20,11587.8,1655.40,Card,Amit
2034,10997,2025-05-21,Customer_2034,Female,40,Mumbai,MH,West,P956,Electronics,Keyboard,7,39196,10,246934.80,192060.4,54874.40,Net Banking,Priya
2217,10998,2025-09-12,Customer_2217,Male,32,Indore,MP,West,P223,Electronics,Laptop,2,39774,0,79548.00,55683.6,23864.40,Net Banking,Priya
2220,10999,2025-02-09,Customer_2220,Female,39,Mumbai,MH,West,P602,Grocery,Sugar,8,48968,0,391744.00,274220.8,117523.20,UPI,Amit
2058,11000,2025-01-02,Customer_2058,Male,45,Indore,MP,West,P478,Electronics,Laptop,5,17572,20,70288.00,61502.0,8786.00,UPI,Neha

In [34]:
df.reset_index(drop = True, inplace = False)

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
0,10001,2025-12-27,2271,Customer_2271,Female,52,Gwalior,MP,North,P662,Clothing,Jeans,1,40160,5,38152.00,28112.0,10040.00,Card,Rahul
1,10002,2025-08-12,2194,Customer_2194,Male,53,Indore,MP,West,P566,Furniture,Table,1,29341,5,27873.95,20538.7,7335.25,Cash,Neha
2,10003,2025-05-08,2135,Customer_2135,Male,27,Lucknow,UP,North,P966,Electronics,Laptop,3,38968,15,99368.40,81832.8,17535.60,UPI,Amit
3,10004,2025-07-18,2137,Customer_2137,Male,27,Indore,MP,West,P754,Furniture,Table,10,29099,10,261891.00,203693.0,58198.00,Card,Neha
4,10005,2025-04-29,2071,Customer_2071,Male,31,Gwalior,MP,North,P467,Clothing,Jeans,3,27041,15,68954.55,56786.1,12168.45,UPI,Karan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10996,2025-08-21,2062,Customer_2062,Female,48,Delhi,Delhi,North,P746,Clothing,Jacket,6,2759,20,13243.20,11587.8,1655.40,Card,Amit
996,10997,2025-05-21,2034,Customer_2034,Female,40,Mumbai,MH,West,P956,Electronics,Keyboard,7,39196,10,246934.80,192060.4,54874.40,Net Banking,Priya
997,10998,2025-09-12,2217,Customer_2217,Male,32,Indore,MP,West,P223,Electronics,Laptop,2,39774,0,79548.00,55683.6,23864.40,Net Banking,Priya
998,10999,2025-02-09,2220,Customer_2220,Female,39,Mumbai,MH,West,P602,Grocery,Sugar,8,48968,0,391744.00,274220.8,117523.20,UPI,Amit
999,11000,2025-01-02,2058,Customer_2058,Male,45,Indore,MP,West,P478,Electronics,Laptop,5,17572,20,70288.00,61502.0,8786.00,UPI,Neha

In [35]:
df.isnull()

,OrderID,OrderDate,CustomerID,CustomerName,Gender,Age,City,State,Region,ProductID,Category,Product,Quantity,UnitPrice,DiscountPct,Sales,Cost,Profit,PaymentMode,SalesPerson
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [36]:
df.isnull().sum()

OrderID         0
OrderDate       0
CustomerID      0
CustomerName    0
Gender          0
Age             0
City            0
State           0
Region          0
ProductID       0
Category        0
Product         0
Quantity        0
UnitPrice       0
DiscountPct     0
Sales           0
Cost            0
Profit          0
PaymentMode     0
SalesPerson     0
dtype: int64

In [ ]:
df.dropna(inplace = True)