# concate & Merge data

In [1]:
import pandas as pd

In [2]:
# 1. Concatenate (DataFrames ko jodna)

# 👉 concat() ka use hota hai:

# Multiple DataFrames ko stack (upar-neeche ya side-by-side) jodne ke liye
# pd.concat([df1, df2])

In [4]:
df1 = pd.DataFrame({
    "Name" : ["Ram" , "Ravi"],
    "Age" : [25,30]
})

df2 = pd.DataFrame({
    "Name" : ["Amit", "Sita"],
    "Age" : [28, 22]
})

result = pd.concat([df1 , df2], axis = 0)  # conact Vertical / row wise
# result = pd.concat([df1 , df2], axis = 1)  # concat Horizontal / column wise
result

   Name  Age
0   Ram   25
1  Ravi   30
0  Amit   28
1  Sita   22

In [6]:
# Merge in pandas 
# merge on comman colimn like sql
df1 = pd.DataFrame({
    "emp_id" : [1,2,3],
    "Name" : ['Ram', 'Ravi', 'Amit']
})

df2 = pd.DataFrame({
    "emp_id" : [1,2,4],
    "Salary" : [30000, 40000, 50000]
})

In [7]:
 pd.merge(df1, df2, on = "emp_id")  # inner join

   emp_id  Name  Salary
0       1   Ram   30000
1       2  Ravi   40000

In [8]:
pd.merge(df1, df2, on = "emp_id", how = "left")   # left join

   emp_id  Name   Salary
0       1   Ram  30000.0
1       2  Ravi  40000.0
2       3  Amit      NaN

In [10]:
pd.merge(df1, df2, on = "emp_id", how = "right")   # Right join

   emp_id  Name  Salary
0       1   Ram   30000
1       2  Ravi   40000
2       4   NaN   50000

In [12]:
pd.merge(df1, df2, on = "emp_id", how = "outer")   # Full join

   emp_id  Name   Salary
0       1   Ram  30000.0
1       2  Ravi  40000.0
2       3  Amit      NaN
3       4   NaN  50000.0

In [14]:

# Join Type	Result
# Inner	Only matching
# Left	Left + matching right
# Right	Right + matching left
# Outer	All data  # Right join

In [19]:
pd.merge(df1, df2, how = "inner", left_on = "emp_id", right_on = "emp_id")   # dono table m alag data ho tab

   emp_id  Name  Salary
0       1   Ram   30000
1       2  Ravi   40000

In [18]:
pd.merge(df1, df2, how='inner', left_on='emp_id', right_on='emp_id')  #dono table mai name alag ho tab

   emp_id  Name  Salary
0       1   Ram   30000
1       2  Ravi   40000