In [2]:
import pandas as pd

In [3]:
emp_data = {
    "Name": [
        "Aman", "Riya", "Rahul", "Sneha", "Arjun",
        "Pooja", "Karan", "Neha", "Vikas", "Simran",
        "Ankit", "Priya", "Rohit", "Meena", "Sahil",
        "Kavya", "Deepak", "Nisha", "Yash", "Tina"
    ],

    "Age": [
        24, 26, 28, 25, 30,
        27, 29, 23, 31, 26,
        28, 24, 32, 27, 29,
        25, 33, 26, 30, 24
    ],

    "Salary": [
        25000, 32000, 40000, 28000, 50000,
        35000, 42000, 26000, 55000, 33000,
        41000, 27000, 60000, 36000, 45000,
        30000, 65000, 34000, 48000, 29000
    ],
    "Performance_Score": [
        78, 85, 90, 76, 95,
        88, 82, 74, 96, 80,
        89, 77, 98, 84, 91,
        79, 99, 83, 92, 75
    ]
}

In [4]:
df = pd.DataFrame(emp_data)

In [5]:
df

      Name  Age  Salary  Performance_Score
0     Aman   24   25000                 78
1     Riya   26   32000                 85
2    Rahul   28   40000                 90
3    Sneha   25   28000                 76
4    Arjun   30   50000                 95
5    Pooja   27   35000                 88
6    Karan   29   42000                 82
7     Neha   23   26000                 74
8    Vikas   31   55000                 96
9   Simran   26   33000                 80
10   Ankit   28   41000                 89
11   Priya   24   27000                 77
12   Rohit   32   60000                 98
13   Meena   27   36000                 84
14   Sahil   29   45000                 91
15   Kavya   25   30000                 79
16  Deepak   33   65000                 99
17   Nisha   26   34000                 83
18    Yash   30   48000                 92
19    Tina   24   29000                 75

# adding a column

In [6]:
df["Bonus"] = df["Salary"] * 0.1
print(df)

      Name  Age  Salary  Performance_Score   Bonus
0     Aman   24   25000                 78  2500.0
1     Riya   26   32000                 85  3200.0
2    Rahul   28   40000                 90  4000.0
3    Sneha   25   28000                 76  2800.0
4    Arjun   30   50000                 95  5000.0
5    Pooja   27   35000                 88  3500.0
6    Karan   29   42000                 82  4200.0
7     Neha   23   26000                 74  2600.0
8    Vikas   31   55000                 96  5500.0
9   Simran   26   33000                 80  3300.0
10   Ankit   28   41000                 89  4100.0
11   Priya   24   27000                 77  2700.0
12   Rohit   32   60000                 98  6000.0
13   Meena   27   36000                 84  3600.0
14   Sahil   29   45000                 91  4500.0
15   Kavya   25   30000                 79  3000.0
16  Deepak   33   65000                 99  6500.0
17   Nisha   26   34000                 83  3400.0
18    Yash   30   48000                 92  4800.0
19    Tina   24   29000                 75  2900.0

In [7]:
# insert a column to specific position
df.insert(0,"emp_id",[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
df

    emp_id    Name  Age  Salary  Performance_Score   Bonus
0        1    Aman   24   25000                 78  2500.0
1        2    Riya   26   32000                 85  3200.0
2        3   Rahul   28   40000                 90  4000.0
3        4   Sneha   25   28000                 76  2800.0
4        5   Arjun   30   50000                 95  5000.0
5        6   Pooja   27   35000                 88  3500.0
6        7   Karan   29   42000                 82  4200.0
7        8    Neha   23   26000                 74  2600.0
8        9   Vikas   31   55000                 96  5500.0
9       10  Simran   26   33000                 80  3300.0
10      11   Ankit   28   41000                 89  4100.0
11      12   Priya   24   27000                 77  2700.0
12      13   Rohit   32   60000                 98  6000.0
13      14   Meena   27   36000                 84  3600.0
14      15   Sahil   29   45000                 91  4500.0
15      16   Kavya   25   30000                 79  3000.0
16      17  Deepak   33   65000                 99  6500.0
17      18   Nisha   26   34000                 83  3400.0
18      19    Yash   30   48000                 92  4800.0
19      20    Tina   24   29000                 75  2900.0

# Updating data

In [8]:
# updating value or a row
df.loc[0]

emp_id                    1
Name                   Aman
Age                      24
Salary                25000
Performance_Score        78
Bonus                2500.0
Name: 0, dtype: object

In [9]:
df.loc[0,"Salary"] = 35000
df.loc[0]

emp_id                    1
Name                   Aman
Age                      24
Salary                35000
Performance_Score        78
Bonus                2500.0
Name: 0, dtype: object

In [10]:
# updating a column 
df["Salary"] = df["Salary"]*0.2
df["Salary"]

0      7000.0
1      6400.0
2      8000.0
3      5600.0
4     10000.0
5      7000.0
6      8400.0
7      5200.0
8     11000.0
9      6600.0
10     8200.0
11     5400.0
12    12000.0
13     7200.0
14     9000.0
15     6000.0
16    13000.0
17     6800.0
18     9600.0
19     5800.0
Name: Salary, dtype: float64

# Sort Data

In [11]:
df

    emp_id    Name  Age   Salary  Performance_Score   Bonus
0        1    Aman   24   7000.0                 78  2500.0
1        2    Riya   26   6400.0                 85  3200.0
2        3   Rahul   28   8000.0                 90  4000.0
3        4   Sneha   25   5600.0                 76  2800.0
4        5   Arjun   30  10000.0                 95  5000.0
5        6   Pooja   27   7000.0                 88  3500.0
6        7   Karan   29   8400.0                 82  4200.0
7        8    Neha   23   5200.0                 74  2600.0
8        9   Vikas   31  11000.0                 96  5500.0
9       10  Simran   26   6600.0                 80  3300.0
10      11   Ankit   28   8200.0                 89  4100.0
11      12   Priya   24   5400.0                 77  2700.0
12      13   Rohit   32  12000.0                 98  6000.0
13      14   Meena   27   7200.0                 84  3600.0
14      15   Sahil   29   9000.0                 91  4500.0
15      16   Kavya   25   6000.0                 79  3000.0
16      17  Deepak   33  13000.0                 99  6500.0
17      18   Nisha   26   6800.0                 83  3400.0
18      19    Yash   30   9600.0                 92  4800.0
19      20    Tina   24   5800.0                 75  2900.0

In [12]:
df.sort_values(by = "Age", ascending = True , inplace = False)  # sort data by age

    emp_id    Name  Age   Salary  Performance_Score   Bonus
7        8    Neha   23   5200.0                 74  2600.0
0        1    Aman   24   7000.0                 78  2500.0
11      12   Priya   24   5400.0                 77  2700.0
19      20    Tina   24   5800.0                 75  2900.0
15      16   Kavya   25   6000.0                 79  3000.0
3        4   Sneha   25   5600.0                 76  2800.0
1        2    Riya   26   6400.0                 85  3200.0
9       10  Simran   26   6600.0                 80  3300.0
17      18   Nisha   26   6800.0                 83  3400.0
5        6   Pooja   27   7000.0                 88  3500.0
13      14   Meena   27   7200.0                 84  3600.0
10      11   Ankit   28   8200.0                 89  4100.0
2        3   Rahul   28   8000.0                 90  4000.0
6        7   Karan   29   8400.0                 82  4200.0
14      15   Sahil   29   9000.0                 91  4500.0
4        5   Arjun   30  10000.0                 95  5000.0
18      19    Yash   30   9600.0                 92  4800.0
8        9   Vikas   31  11000.0                 96  5500.0
12      13   Rohit   32  12000.0                 98  6000.0
16      17  Deepak   33  13000.0                 99  6500.0

In [13]:
# sort multiple columns 
df.sort_values(["Age","Salary"], ascending = True, inplace = False)

    emp_id    Name  Age   Salary  Performance_Score   Bonus
7        8    Neha   23   5200.0                 74  2600.0
11      12   Priya   24   5400.0                 77  2700.0
19      20    Tina   24   5800.0                 75  2900.0
0        1    Aman   24   7000.0                 78  2500.0
3        4   Sneha   25   5600.0                 76  2800.0
15      16   Kavya   25   6000.0                 79  3000.0
1        2    Riya   26   6400.0                 85  3200.0
9       10  Simran   26   6600.0                 80  3300.0
17      18   Nisha   26   6800.0                 83  3400.0
5        6   Pooja   27   7000.0                 88  3500.0
13      14   Meena   27   7200.0                 84  3600.0
2        3   Rahul   28   8000.0                 90  4000.0
10      11   Ankit   28   8200.0                 89  4100.0
6        7   Karan   29   8400.0                 82  4200.0
14      15   Sahil   29   9000.0                 91  4500.0
18      19    Yash   30   9600.0                 92  4800.0
4        5   Arjun   30  10000.0                 95  5000.0
8        9   Vikas   31  11000.0                 96  5500.0
12      13   Rohit   32  12000.0                 98  6000.0
16      17  Deepak   33  13000.0                 99  6500.0

In [14]:
df

    emp_id    Name  Age   Salary  Performance_Score   Bonus
0        1    Aman   24   7000.0                 78  2500.0
1        2    Riya   26   6400.0                 85  3200.0
2        3   Rahul   28   8000.0                 90  4000.0
3        4   Sneha   25   5600.0                 76  2800.0
4        5   Arjun   30  10000.0                 95  5000.0
5        6   Pooja   27   7000.0                 88  3500.0
6        7   Karan   29   8400.0                 82  4200.0
7        8    Neha   23   5200.0                 74  2600.0
8        9   Vikas   31  11000.0                 96  5500.0
9       10  Simran   26   6600.0                 80  3300.0
10      11   Ankit   28   8200.0                 89  4100.0
11      12   Priya   24   5400.0                 77  2700.0
12      13   Rohit   32  12000.0                 98  6000.0
13      14   Meena   27   7200.0                 84  3600.0
14      15   Sahil   29   9000.0                 91  4500.0
15      16   Kavya   25   6000.0                 79  3000.0
16      17  Deepak   33  13000.0                 99  6500.0
17      18   Nisha   26   6800.0                 83  3400.0
18      19    Yash   30   9600.0                 92  4800.0
19      20    Tina   24   5800.0                 75  2900.0

In [16]:
df["Name"].str.contains("Aman").sum()

np.int64(1)

In [18]:
df["Name"].str.contains("n").sum()

np.int64(8)

In [19]:
df["Name"].str.upper()

0       AMAN
1       RIYA
2      RAHUL
3      SNEHA
4      ARJUN
5      POOJA
6      KARAN
7       NEHA
8      VIKAS
9     SIMRAN
10     ANKIT
11     PRIYA
12     ROHIT
13     MEENA
14     SAHIL
15     KAVYA
16    DEEPAK
17     NISHA
18      YASH
19      TINA
Name: Name, dtype: str

In [21]:
df["Name"].str.lower()

0       aman
1       riya
2      rahul
3      sneha
4      arjun
5      pooja
6      karan
7       neha
8      vikas
9     simran
10     ankit
11     priya
12     rohit
13     meena
14     sahil
15     kavya
16    deepak
17     nisha
18      yash
19      tina
Name: Name, dtype: str

In [22]:
df["Name"].str.title()

0       Aman
1       Riya
2      Rahul
3      Sneha
4      Arjun
5      Pooja
6      Karan
7       Neha
8      Vikas
9     Simran
10     Ankit
11     Priya
12     Rohit
13     Meena
14     Sahil
15     Kavya
16    Deepak
17     Nisha
18      Yash
19      Tina
Name: Name, dtype: str

In [25]:
df['Name'].str.islower()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: Name, dtype: bool

In [26]:
df["Name"].str.istitle()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
Name: Name, dtype: bool

In [28]:
df["Name"].str.replace("Aman","xyz")

0        xyz
1       Riya
2      Rahul
3      Sneha
4      Arjun
5      Pooja
6      Karan
7       Neha
8      Vikas
9     Simran
10     Ankit
11     Priya
12     Rohit
13     Meena
14     Sahil
15     Kavya
16    Deepak
17     Nisha
18      Yash
19      Tina
Name: Name, dtype: str

In [31]:
import pandas as pd
data = {'Email': ['user@gmail.com', 'admin@yahoo.com']}
df = pd.DataFrame(data)
df

             Email
0   user@gmail.com
1  admin@yahoo.com

In [32]:
# Filtering records based on substring match criteria logic
df['Email'].str.contains('gmail')

0     True
1    False
Name: Email, dtype: bool