# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index.

In [1]:
import pandas as pd
import numpy as np

In [2]:
from numpy.random import randn
# np.random.seed(101)

In [3]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [4]:
df

          W         X         Y         Z
A  1.276114 -0.840237  1.113110  0.051738
B -0.043290 -0.589316 -0.143914  0.326277
C  0.132655 -0.797223  0.081762  1.354335
D  0.800750 -0.625803 -0.012342 -0.213905
E  0.333289 -0.219322 -0.692062  0.097762

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [5]:
df['W']

A    1.276114
B   -0.043290
C    0.132655
D    0.800750
E    0.333289
Name: W, dtype: float64

In [6]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A  1.276114  0.051738
B -0.043290  0.326277
C  0.132655  1.354335
D  0.800750 -0.213905
E  0.333289  0.097762

In [ ]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

DataFrame Columns are just Series

In [7]:
type(df['W'])

pandas.Series

**Creating a new column:**

In [8]:
df['new'] = df['W'] + df['Y']

In [9]:
df

          W         X         Y         Z       new
A  1.276114 -0.840237  1.113110  0.051738  2.389224
B -0.043290 -0.589316 -0.143914  0.326277 -0.187204
C  0.132655 -0.797223  0.081762  1.354335  0.214417
D  0.800750 -0.625803 -0.012342 -0.213905  0.788408
E  0.333289 -0.219322 -0.692062  0.097762 -0.358772

** Removing Columns**

In [10]:
df.drop('new',axis=1)

          W         X         Y         Z
A  1.276114 -0.840237  1.113110  0.051738
B -0.043290 -0.589316 -0.143914  0.326277
C  0.132655 -0.797223  0.081762  1.354335
D  0.800750 -0.625803 -0.012342 -0.213905
E  0.333289 -0.219322 -0.692062  0.097762

In [11]:
# Not inplace unless specified!
df

          W         X         Y         Z       new
A  1.276114 -0.840237  1.113110  0.051738  2.389224
B -0.043290 -0.589316 -0.143914  0.326277 -0.187204
C  0.132655 -0.797223  0.081762  1.354335  0.214417
D  0.800750 -0.625803 -0.012342 -0.213905  0.788408
E  0.333289 -0.219322 -0.692062  0.097762 -0.358772

In [12]:
df.drop('new',axis=1,inplace=True)

In [13]:
df

          W         X         Y         Z
A  1.276114 -0.840237  1.113110  0.051738
B -0.043290 -0.589316 -0.143914  0.326277
C  0.132655 -0.797223  0.081762  1.354335
D  0.800750 -0.625803 -0.012342 -0.213905
E  0.333289 -0.219322 -0.692062  0.097762

Can also drop rows this way:

In [14]:
df.drop('E',axis=0)

          W         X         Y         Z
A  1.276114 -0.840237  1.113110  0.051738
B -0.043290 -0.589316 -0.143914  0.326277
C  0.132655 -0.797223  0.081762  1.354335
D  0.800750 -0.625803 -0.012342 -0.213905

** Selecting Rows**

In [15]:
df.loc['A']

W    1.276114
X   -0.840237
Y    1.113110
Z    0.051738
Name: A, dtype: float64

Or select based off of position instead of label

In [16]:
df.iloc[2]

W    0.132655
X   -0.797223
Y    0.081762
Z    1.354335
Name: C, dtype: float64

** Selecting subset of rows and columns **

In [17]:
df.loc['B','Y']

np.float64(-0.14391390078347963)

In [18]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  1.276114  1.113110
B -0.043290 -0.143914

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [19]:
df

          W         X         Y         Z
A  1.276114 -0.840237  1.113110  0.051738
B -0.043290 -0.589316 -0.143914  0.326277
C  0.132655 -0.797223  0.081762  1.354335
D  0.800750 -0.625803 -0.012342 -0.213905
E  0.333289 -0.219322 -0.692062  0.097762

In [ ]:
df = pd.DataFrame(np.random.randn(5,4),index=list('ABCDE'),columns=list('WXYZ'))
print(df)
df > 0

In [ ]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split()) 
print(df)
df[df>0]

In [ ]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split()) 
print(df)

df[df['W']>0]

In [ ]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split()) 
df[df['W']>0]['Y']

In [ ]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split()) 
df[df['W']>0][['Y','X']]

For two conditions you can use | and & with parenthesis:

In [ ]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
print(df)
df[(df['W']>0) & (df['Y'] > 1)]

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [ ]:
df

In [ ]:
# Reset to default 0,1...n index
df.reset_index()

In [ ]:
newind = 'CA NY WY OR CO'.split()

In [ ]:
df['States'] = newind

In [ ]:
df

In [ ]:
df.set_index('States')

In [ ]:
df

In [ ]:
df.set_index('States',inplace=True)

In [ ]:
df

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [ ]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

In [ ]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [ ]:
df.loc['G1']

In [ ]:
df.loc['G1'].loc[1]

In [ ]:
df.index.names

In [ ]:
df.index.names = ['Group','Num']

In [ ]:
df

In [ ]:
df.xs('G1')

In [ ]:
df.xs(('G1',1))

In [ ]:
df.xs((1,level ='Num'))

# Great Job!

In [5]:
data = { "Name" : ["Ravi","Rihan","Neha","Sonum"],
    "Age" : [22,34,23,11]
}
df1 = pd.DataFrame(data)
df1

    Name  Age
0   Ravi   22
1  Rihan   34
2   Neha   23
3  Sonum   11

In [7]:
data2 = { "Name" : ["Manav","Sonu","ROhit","Sachin"],
    "Age" : [21,32,22,27]
}
df2 = pd.DataFrame(data2)
df2

     Name  Age
0   Manav   21
1    Sonu   32
2   ROhit   22
3  Sachin   27

In [13]:
df = pd.concat([df1,df2], ignore_index = True)
df

     Name  Age
0    Ravi   22
1   Rihan   34
2    Neha   23
3   Sonum   11
4   Manav   21
5    Sonu   32
6   ROhit   22
7  Sachin   27

In [15]:
df.head()

    Name  Age
0   Ravi   22
1  Rihan   34
2   Neha   23
3  Sonum   11
4  Manav   21

In [16]:
df.tail()

     Name  Age
3   Sonum   11
4   Manav   21
5    Sonu   32
6   ROhit   22
7  Sachin   27

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      str
 1   Age     8 non-null      int64
dtypes: int64(1), str(1)
memory usage: 260.0 bytes

In [19]:
df.describe()

             Age
count   8.000000
mean   24.000000
std     7.171372
min    11.000000
25%    21.750000
50%    22.500000
75%    28.250000
max    34.000000

In [22]:
df = pd.concat([df1,df2], ignore_index = True, axis = 1)
df

       0   1       2   3
0   Ravi  22   Manav  21
1  Rihan  34    Sonu  32
2   Neha  23   ROhit  22
3  Sonum  11  Sachin  27

In [27]:
import pandas as pd
data = {'Year': [2021, 2021, 2022, 2022], 
        'Region': ['East', 'West', 'East', 'West'], 
        'Revenue': [10, 15, 20, 30],
       "Age" : [22,21,23,24]}
df = pd.DataFrame(data)
df

   Year Region  Revenue  Age
0  2021   East       10   22
1  2021   West       15   21
2  2022   East       20   23
3  2022   West       30   24

In [32]:
df.pivot_table(values='Age', index='Year', columns='Region', aggfunc='sum')

Region  East  West
Year
2021      22    21
2022      23    24