In [1]:
import pandas as pd

In [2]:
emp_data = {
    "Name": [
        "Aman", None, "Rahul", "Sneha", "Arjun",
        "Pooja", "Karan", "Neha", "Vikas", None,
        None, "Priya", "Rohit", "Meena", "Sahil",
        "Kavya", "Deepak", None, "Yash", "Tina"
    ],

    "Age": [
        None, 26, 28, 25, 30,
        27, 29, None, 31, 26,
        28, None, 32, 27, 29,
        25, 33, 26, None, 24
    ],

    "Salary": [
        25000, 32000, None, 28000, 50000,
        None, 42000, 26000, 55000, 33000,
        41000, 27000, None, 36000, 45000,
        30000, 65000, 34000, 48000, None
    ],
    "Performance_Score": [
        None, 85, 90, 76, 95,
        88, 82, 74, None, 80,
        None, 77, 98, 84, 91,
        79, 99, 83, None, 75
    ]
}

In [3]:
df = pd.DataFrame(emp_data)
df

      Name   Age   Salary  Performance_Score
0     Aman   NaN  25000.0                NaN
1      NaN  26.0  32000.0               85.0
2    Rahul  28.0      NaN               90.0
3    Sneha  25.0  28000.0               76.0
4    Arjun  30.0  50000.0               95.0
5    Pooja  27.0      NaN               88.0
6    Karan  29.0  42000.0               82.0
7     Neha   NaN  26000.0               74.0
8    Vikas  31.0  55000.0                NaN
9      NaN  26.0  33000.0               80.0
10     NaN  28.0  41000.0                NaN
11   Priya   NaN  27000.0               77.0
12   Rohit  32.0      NaN               98.0
13   Meena  27.0  36000.0               84.0
14   Sahil  29.0  45000.0               91.0
15   Kavya  25.0  30000.0               79.0
16  Deepak  33.0  65000.0               99.0
17     NaN  26.0  34000.0               83.0
18    Yash   NaN  48000.0                NaN
19    Tina  24.0      NaN               75.0

In [4]:
# check null data
df.isnull()

     Name    Age  Salary  Performance_Score
0   False   True   False               True
1    True  False   False              False
2   False  False    True              False
3   False  False   False              False
4   False  False   False              False
5   False  False    True              False
6   False  False   False              False
7   False   True   False              False
8   False  False   False               True
9    True  False   False              False
10   True  False   False               True
11  False   True   False              False
12  False  False    True              False
13  False  False   False              False
14  False  False   False              False
15  False  False   False              False
16  False  False   False              False
17   True  False   False              False
18  False   True   False               True
19  False  False    True              False

In [5]:
# count of missing value
df.isnull().sum()

Name                 4
Age                  4
Salary               4
Performance_Score    4
dtype: int64

In [6]:
# remove missing data
df.dropna(axis = 0, inplace = True)
df

      Name   Age   Salary  Performance_Score
3    Sneha  25.0  28000.0               76.0
4    Arjun  30.0  50000.0               95.0
6    Karan  29.0  42000.0               82.0
13   Meena  27.0  36000.0               84.0
14   Sahil  29.0  45000.0               91.0
15   Kavya  25.0  30000.0               79.0
16  Deepak  33.0  65000.0               99.0

# fill value on null data

In [7]:
df.fillna(3, inplace = True)
df

      Name   Age   Salary  Performance_Score
3    Sneha  25.0  28000.0               76.0
4    Arjun  30.0  50000.0               95.0
6    Karan  29.0  42000.0               82.0
13   Meena  27.0  36000.0               84.0
14   Sahil  29.0  45000.0               91.0
15   Kavya  25.0  30000.0               79.0
16  Deepak  33.0  65000.0               99.0

In [8]:
 # fill calculate value
df["Age"].fillna(df["Age"].mean())

3     25.0
4     30.0
6     29.0
13    27.0
14    29.0
15    25.0
16    33.0
Name: Age, dtype: float64

In [9]:
df["Salary"].fillna(df["Salary"].mean())

3     28000.0
4     50000.0
6     42000.0
13    36000.0
14    45000.0
15    30000.0
16    65000.0
Name: Salary, dtype: float64