In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\VipStar\AppData\Roaming\Python\Python314\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\VipStar\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\VipStar\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\VipStar\AppData\Roaming\Python\Python314\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\VipStar\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John","Nazzu","Rani","Rahul","Neha"],
    "Age": [20, 22, 21,22,24,23,21],
    "Marks": [85, 90, 88, 78, 67, 89, 69]
}

df = pd.DataFrame(data)

print("Original Data")
print(df)

Original Data
    Name  Age  Marks
0    Ali   20     85
1   Sara   22     90
2   John   21     88
3  Nazzu   22     78
4   Rani   24     67
5  Rahul   23     89
6   Neha   21     69

In [12]:
print(df.head(3))

   Name  Age  Marks
0   Ali   20     85
1  Sara   22     90
2  John   21     88

In [14]:
print(df.tail(2))

    Name  Age  Marks
5  Rahul   23     89
6   Neha   21     69

In [16]:
print(df.shape)

(7, 3)

In [17]:
print(df.columns)

Index(['Name', 'Age', 'Marks'], dtype='str')

In [20]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     7 non-null      int64
 2   Marks   7 non-null      int64
dtypes: int64(2), str(1)
memory usage: 300.0 bytes
None

In [21]:
print(df.describe())

             Age      Marks
count   7.000000   7.000000
mean   21.857143  80.857143
std     1.345185   9.651055
min    20.000000  67.000000
25%    21.000000  73.500000
50%    22.000000  85.000000
75%    22.500000  88.500000
max    24.000000  90.000000

In [23]:
print(df["Name"])

0      Ali
1     Sara
2     John
3    Nazzu
4     Rani
5    Rahul
6     Neha
Name: Name, dtype: str

In [24]:
print(df[["Name","Age"]])

    Name  Age
0    Ali   20
1   Sara   22
2   John   21
3  Nazzu   22
4   Rani   24
5  Rahul   23
6   Neha   21

In [31]:
print(df.loc[0])

Name     Ali
Age       20
Marks     85
Name: 0, dtype: object

In [30]:
print(df.iloc[0])

Name     Ali
Age       20
Marks     85
Name: 0, dtype: object

In [32]:
import numpy as np
import pandas as pd
from numpy.random import randn
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split()) 
df

          W         X         Y         Z
A  2.773878 -2.112441  0.779621  2.267994
B -0.489050  0.057680 -0.856758 -0.719547
C -2.629333  0.109650 -0.554557 -1.077805
D -3.101698 -0.760884  0.529160  0.833068
E  0.624393  0.137380  0.232644 -0.630196

In [34]:
df["W"]

A    2.773878
B   -0.489050
C   -2.629333
D   -3.101698
E    0.624393
Name: W, dtype: float64

In [36]:
df[["W","Z"]]

          W         Z
A  2.773878  2.267994
B -0.489050 -0.719547
C -2.629333 -1.077805
D -3.101698  0.833068
E  0.624393 -0.630196

In [38]:
type(df["W"])

pandas.Series

In [40]:
df = pd.read_csv("Employee.csv")
df

   id    name    sal     city
0   1  Raghav  20000   Indore
1   2   Rahul  15000   Jhansi
2   3    Rani  25000  Gwalior

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.