In [1]:
import pandas as pd

In [2]:
data = {
    "Name" : ["Ram", "Ravi","John","Rony","Rohit","Sonu","Neha","Rupali","Sanjay","Monu"],
    "Age" : [22,23,21,20,22,25,23,22,21,19],
    "Salary" : [20000,24000,24000,23000,21000,34000,32000,31000,28000,30000]
}
df = pd.DataFrame(data)
print(df)

     Name  Age  Salary
0     Ram   22   20000
1    Ravi   23   24000
2    John   21   24000
3    Rony   20   23000
4   Rohit   22   21000
5    Sonu   25   34000
6    Neha   23   32000
7  Rupali   22   31000
8  Sanjay   21   28000
9    Monu   19   30000

In [3]:
print(df.head(2))

   Name  Age  Salary
0   Ram   22   20000
1  Ravi   23   24000

In [4]:
print(df.tail(2))

     Name  Age  Salary
8  Sanjay   21   28000
9    Monu   19   30000

In [5]:
df.shape

(10, 3)

In [6]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [7]:
df.rename(columns = {"Salary" : "Monthly_Salary"},inplace = True)
print(df)

     Name  Age  Monthly_Salary
0     Ram   22           20000
1    Ravi   23           24000
2    John   21           24000
3    Rony   20           23000
4   Rohit   22           21000
5    Sonu   25           34000
6    Neha   23           32000
7  Rupali   22           31000
8  Sanjay   21           28000
9    Monu   19           30000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            10 non-null     str
 1   Age             10 non-null     int64
 2   Monthly_Salary  10 non-null     int64
dtypes: int64(2), str(1)
memory usage: 372.0 bytes

In [9]:
df.describe()

             Age  Monthly_Salary
count  10.000000       10.000000
mean   21.800000    26700.000000
std     1.686548     4922.736366
min    19.000000    20000.000000
25%    21.000000    23250.000000
50%    22.000000    26000.000000
75%    22.750000    30750.000000
max    25.000000    34000.000000

# save and load data into csv

In [10]:
df.to_csv("pn_data.csv",index = False) #to remove index

In [11]:
df["College"] = ["rjit", "mits","itm", "mpct", "krg", "Vrg", "Mits", "itm", "Mpct", "krg"]
df

     Name  Age  Monthly_Salary College
0     Ram   22           20000    rjit
1    Ravi   23           24000    mits
2    John   21           24000     itm
3    Rony   20           23000    mpct
4   Rohit   22           21000     krg
5    Sonu   25           34000     Vrg
6    Neha   23           32000    Mits
7  Rupali   22           31000     itm
8  Sanjay   21           28000    Mpct
9    Monu   19           30000     krg

In [12]:
df["Bonus"] = df["Monthly_Salary"] * 0.2
df

     Name  Age  Monthly_Salary College   Bonus
0     Ram   22           20000    rjit  4000.0
1    Ravi   23           24000    mits  4800.0
2    John   21           24000     itm  4800.0
3    Rony   20           23000    mpct  4600.0
4   Rohit   22           21000     krg  4200.0
5    Sonu   25           34000     Vrg  6800.0
6    Neha   23           32000    Mits  6400.0
7  Rupali   22           31000     itm  6200.0
8  Sanjay   21           28000    Mpct  5600.0
9    Monu   19           30000     krg  6000.0

In [13]:
df.loc[len(df)] = ["Viki" , 23, 2000, "mpct" , 1000]
df

      Name  Age  Monthly_Salary College   Bonus
0      Ram   22           20000    rjit  4000.0
1     Ravi   23           24000    mits  4800.0
2     John   21           24000     itm  4800.0
3     Rony   20           23000    mpct  4600.0
4    Rohit   22           21000     krg  4200.0
5     Sonu   25           34000     Vrg  6800.0
6     Neha   23           32000    Mits  6400.0
7   Rupali   22           31000     itm  6200.0
8   Sanjay   21           28000    Mpct  5600.0
9     Monu   19           30000     krg  6000.0
10    Viki   23            2000    mpct  1000.0

In [14]:
df.loc[0, "Monthly_Salary"] = 30000
df

      Name  Age  Monthly_Salary College   Bonus
0      Ram   22           30000    rjit  4000.0
1     Ravi   23           24000    mits  4800.0
2     John   21           24000     itm  4800.0
3     Rony   20           23000    mpct  4600.0
4    Rohit   22           21000     krg  4200.0
5     Sonu   25           34000     Vrg  6800.0
6     Neha   23           32000    Mits  6400.0
7   Rupali   22           31000     itm  6200.0
8   Sanjay   21           28000    Mpct  5600.0
9     Monu   19           30000     krg  6000.0
10    Viki   23            2000    mpct  1000.0

In [15]:
df.loc[df.Name == "Ram","Monthly_Salary"] = 11000
df

      Name  Age  Monthly_Salary College   Bonus
0      Ram   22           11000    rjit  4000.0
1     Ravi   23           24000    mits  4800.0
2     John   21           24000     itm  4800.0
3     Rony   20           23000    mpct  4600.0
4    Rohit   22           21000     krg  4200.0
5     Sonu   25           34000     Vrg  6800.0
6     Neha   23           32000    Mits  6400.0
7   Rupali   22           31000     itm  6200.0
8   Sanjay   21           28000    Mpct  5600.0
9     Monu   19           30000     krg  6000.0
10    Viki   23            2000    mpct  1000.0

In [16]:
# delete row
df = df.drop(df[df.Name == "Viki"].index )

In [17]:
df

     Name  Age  Monthly_Salary College   Bonus
0     Ram   22           11000    rjit  4000.0
1    Ravi   23           24000    mits  4800.0
2    John   21           24000     itm  4800.0
3    Rony   20           23000    mpct  4600.0
4   Rohit   22           21000     krg  4200.0
5    Sonu   25           34000     Vrg  6800.0
6    Neha   23           32000    Mits  6400.0
7  Rupali   22           31000     itm  6200.0
8  Sanjay   21           28000    Mpct  5600.0
9    Monu   19           30000     krg  6000.0

In [18]:
df.drop(1,axis = 0)

     Name  Age  Monthly_Salary College   Bonus
0     Ram   22           11000    rjit  4000.0
2    John   21           24000     itm  4800.0
3    Rony   20           23000    mpct  4600.0
4   Rohit   22           21000     krg  4200.0
5    Sonu   25           34000     Vrg  6800.0
6    Neha   23           32000    Mits  6400.0
7  Rupali   22           31000     itm  6200.0
8  Sanjay   21           28000    Mpct  5600.0
9    Monu   19           30000     krg  6000.0

In [19]:
#delete columns
# df.drop("Bonus", axis = 1, inplace = True)
df.drop(["Bonus","College"], axis = 1, inplace = True)
df

     Name  Age  Monthly_Salary
0     Ram   22           11000
1    Ravi   23           24000
2    John   21           24000
3    Rony   20           23000
4   Rohit   22           21000
5    Sonu   25           34000
6    Neha   23           32000
7  Rupali   22           31000
8  Sanjay   21           28000
9    Monu   19           30000

In [20]:
df

     Name  Age  Monthly_Salary
0     Ram   22           11000
1    Ravi   23           24000
2    John   21           24000
3    Rony   20           23000
4   Rohit   22           21000
5    Sonu   25           34000
6    Neha   23           32000
7  Rupali   22           31000
8  Sanjay   21           28000
9    Monu   19           30000

In [21]:
# rename column name
df.rename(columns = {"Monthly_Salary" : "Salary"}, inplace = True)

In [22]:
df

     Name  Age  Salary
0     Ram   22   11000
1    Ravi   23   24000
2    John   21   24000
3    Rony   20   23000
4   Rohit   22   21000
5    Sonu   25   34000
6    Neha   23   32000
7  Rupali   22   31000
8  Sanjay   21   28000
9    Monu   19   30000

In [23]:
df.sort_values("Salary",ascending = False)

     Name  Age  Salary
5    Sonu   25   34000
6    Neha   23   32000
7  Rupali   22   31000
9    Monu   19   30000
8  Sanjay   21   28000
1    Ravi   23   24000
2    John   21   24000
3    Rony   20   23000
4   Rohit   22   21000
0     Ram   22   11000

# 7 working with date value

In [24]:
# create a date column with date of joining
df["Doj2"] = ["2024-01-01", "2024-01-05","2024-01-10", "2024-01-06", "2024-01-09" ,"2024-01-08", "2024-01-02", 
              "2024-01-04","2024-01-07", "2024-01-12"]
df

     Name  Age  Salary        Doj2
0     Ram   22   11000  2024-01-01
1    Ravi   23   24000  2024-01-05
2    John   21   24000  2024-01-10
3    Rony   20   23000  2024-01-06
4   Rohit   22   21000  2024-01-09
5    Sonu   25   34000  2024-01-08
6    Neha   23   32000  2024-01-02
7  Rupali   22   31000  2024-01-04
8  Sanjay   21   28000  2024-01-07
9    Monu   19   30000  2024-01-12

In [25]:
# check type
df["Doj2"].dtype

In [26]:
df["Doj2"] = pd.to_datetime(df["Doj2"])  # chnge dtype

In [27]:
df["Doj2"].dtype

dtype('<M8[us]')

In [28]:
df1 = df

In [29]:
df1["DOJ23"] = ["01-01-2025", "02-01-2025", "02-01-2025", "04-01-2025", "05-01-2025", "06-01-2025", "07-01-2025", 
                "08-01-2025", "09-01-2025", "10-01-2025" ] 
df1

     Name  Age  Salary       Doj2       DOJ23
0     Ram   22   11000 2024-01-01  01-01-2025
1    Ravi   23   24000 2024-01-05  02-01-2025
2    John   21   24000 2024-01-10  02-01-2025
3    Rony   20   23000 2024-01-06  04-01-2025
4   Rohit   22   21000 2024-01-09  05-01-2025
5    Sonu   25   34000 2024-01-08  06-01-2025
6    Neha   23   32000 2024-01-02  07-01-2025
7  Rupali   22   31000 2024-01-04  08-01-2025
8  Sanjay   21   28000 2024-01-07  09-01-2025
9    Monu   19   30000 2024-01-12  10-01-2025

In [30]:
df1["DOJ23"].dtype

In [31]:
df1["DOJ23"] = pd.to_datetime(df1["DOJ23"], format = '%d-%m-%y') # change date formate
df1["DOJ23"].dtype

ValueError: unconverted data remains when parsing with format "%d-%m-%y": "25". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [32]:
df1

     Name  Age  Salary       Doj2       DOJ23
0     Ram   22   11000 2024-01-01  01-01-2025
1    Ravi   23   24000 2024-01-05  02-01-2025
2    John   21   24000 2024-01-10  02-01-2025
3    Rony   20   23000 2024-01-06  04-01-2025
4   Rohit   22   21000 2024-01-09  05-01-2025
5    Sonu   25   34000 2024-01-08  06-01-2025
6    Neha   23   32000 2024-01-02  07-01-2025
7  Rupali   22   31000 2024-01-04  08-01-2025
8  Sanjay   21   28000 2024-01-07  09-01-2025
9    Monu   19   30000 2024-01-12  10-01-2025

In [33]:
# extract year, date, month, week
# df["DOJ23"].dt.year
# df["DOJ23"].dt.month
# df["DOJ23"].dt.day
# df["DOJ23"].dt.day_name()

In [34]:
df["Doj2"] + pd.Timedelta(days = 90)  # add 90 days to doj column

0   2024-03-31
1   2024-04-04
2   2024-04-09
3   2024-04-05
4   2024-04-08
5   2024-04-07
6   2024-04-01
7   2024-04-03
8   2024-04-06
9   2024-04-11
Name: Doj2, dtype: datetime64[us]

In [35]:
# 8 handling missing values

In [36]:
df

     Name  Age  Salary       Doj2       DOJ23
0     Ram   22   11000 2024-01-01  01-01-2025
1    Ravi   23   24000 2024-01-05  02-01-2025
2    John   21   24000 2024-01-10  02-01-2025
3    Rony   20   23000 2024-01-06  04-01-2025
4   Rohit   22   21000 2024-01-09  05-01-2025
5    Sonu   25   34000 2024-01-08  06-01-2025
6    Neha   23   32000 2024-01-02  07-01-2025
7  Rupali   22   31000 2024-01-04  08-01-2025
8  Sanjay   21   28000 2024-01-07  09-01-2025
9    Monu   19   30000 2024-01-12  10-01-2025

In [37]:
df.isnull()  # Detect missing values

    Name    Age  Salary   Doj2  DOJ23
0  False  False   False  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False   False  False  False
4  False  False   False  False  False
5  False  False   False  False  False
6  False  False   False  False  False
7  False  False   False  False  False
8  False  False   False  False  False
9  False  False   False  False  False

In [38]:
import numpy as np
df.loc[df.Name == "Sonu", "Salary"] = np.nan  # adding a null value
df

     Name  Age   Salary       Doj2       DOJ23
0     Ram   22  11000.0 2024-01-01  01-01-2025
1    Ravi   23  24000.0 2024-01-05  02-01-2025
2    John   21  24000.0 2024-01-10  02-01-2025
3    Rony   20  23000.0 2024-01-06  04-01-2025
4   Rohit   22  21000.0 2024-01-09  05-01-2025
5    Sonu   25      NaN 2024-01-08  06-01-2025
6    Neha   23  32000.0 2024-01-02  07-01-2025
7  Rupali   22  31000.0 2024-01-04  08-01-2025
8  Sanjay   21  28000.0 2024-01-07  09-01-2025
9    Monu   19  30000.0 2024-01-12  10-01-2025

In [39]:
df.isnull()

    Name    Age  Salary   Doj2  DOJ23
0  False  False   False  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False   False  False  False
4  False  False   False  False  False
5  False  False    True  False  False
6  False  False   False  False  False
7  False  False   False  False  False
8  False  False   False  False  False
9  False  False   False  False  False

In [40]:
df.loc[df.Name == "Ram", "Age"] = np.nan   # adding a null value
df

     Name   Age   Salary       Doj2       DOJ23
0     Ram   NaN  11000.0 2024-01-01  01-01-2025
1    Ravi  23.0  24000.0 2024-01-05  02-01-2025
2    John  21.0  24000.0 2024-01-10  02-01-2025
3    Rony  20.0  23000.0 2024-01-06  04-01-2025
4   Rohit  22.0  21000.0 2024-01-09  05-01-2025
5    Sonu  25.0      NaN 2024-01-08  06-01-2025
6    Neha  23.0  32000.0 2024-01-02  07-01-2025
7  Rupali  22.0  31000.0 2024-01-04  08-01-2025
8  Sanjay  21.0  28000.0 2024-01-07  09-01-2025
9    Monu  19.0  30000.0 2024-01-12  10-01-2025

In [41]:
df.isnull().sum()  # count of null values by columns

Name      0
Age       1
Salary    1
Doj2      0
DOJ23     0
dtype: int64

In [42]:
df.fillna(0) # fill null values with 0

     Name   Age   Salary       Doj2       DOJ23
0     Ram   0.0  11000.0 2024-01-01  01-01-2025
1    Ravi  23.0  24000.0 2024-01-05  02-01-2025
2    John  21.0  24000.0 2024-01-10  02-01-2025
3    Rony  20.0  23000.0 2024-01-06  04-01-2025
4   Rohit  22.0  21000.0 2024-01-09  05-01-2025
5    Sonu  25.0      0.0 2024-01-08  06-01-2025
6    Neha  23.0  32000.0 2024-01-02  07-01-2025
7  Rupali  22.0  31000.0 2024-01-04  08-01-2025
8  Sanjay  21.0  28000.0 2024-01-07  09-01-2025
9    Monu  19.0  30000.0 2024-01-12  10-01-2025

In [46]:
df.loc[df.Name == "Ram", "Age"] = 30
df.loc[df.Name.isin(["Ram" ,"Sonu"]), "Salary"] = 20000

In [47]:
df

     Name   Age   Salary       Doj2       DOJ23
0     Ram  30.0  20000.0 2024-01-01  01-01-2025
1    Ravi  23.0  24000.0 2024-01-05  02-01-2025
2    John  21.0  24000.0 2024-01-10  02-01-2025
3    Rony  20.0  23000.0 2024-01-06  04-01-2025
4   Rohit  22.0  21000.0 2024-01-09  05-01-2025
5    Sonu  25.0  20000.0 2024-01-08  06-01-2025
6    Neha  23.0  32000.0 2024-01-02  07-01-2025
7  Rupali  22.0  31000.0 2024-01-04  08-01-2025
8  Sanjay  21.0  28000.0 2024-01-07  09-01-2025
9    Monu  19.0  30000.0 2024-01-12  10-01-2025

In [48]:
df.fillna(0)

     Name   Age   Salary       Doj2       DOJ23
0     Ram  30.0  20000.0 2024-01-01  01-01-2025
1    Ravi  23.0  24000.0 2024-01-05  02-01-2025
2    John  21.0  24000.0 2024-01-10  02-01-2025
3    Rony  20.0  23000.0 2024-01-06  04-01-2025
4   Rohit  22.0  21000.0 2024-01-09  05-01-2025
5    Sonu  25.0  20000.0 2024-01-08  06-01-2025
6    Neha  23.0  32000.0 2024-01-02  07-01-2025
7  Rupali  22.0  31000.0 2024-01-04  08-01-2025
8  Sanjay  21.0  28000.0 2024-01-07  09-01-2025
9    Monu  19.0  30000.0 2024-01-12  10-01-2025