# Operations

There are lots of operations with pandas that will be really useful to you, but don't fall into any distinct category. Let's show them here in this lecture:

In [7]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4,9,6],'col2':[444,555,666,444,888,666],'col3':['abc','def','ghi','xyz','wer','qwe']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz
4     9   888  wer

### Info on Unique Values

In [4]:
df['col2'].unique()

array([444, 555, 666, 888])

In [5]:
df['col2'].nunique()

4

In [8]:
df['col2'].value_counts()

col2
444    2
666    2
555    1
888    1
Name: count, dtype: int64

### Selecting Data

In [9]:
#Select from DataFrame using criteria from multiple columns
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [10]:
newdf

   col1  col2 col3
3     4   444  xyz

### Applying Functions

In [1]:
def times2(x):
    return x*2

In [11]:
df['col1'].apply(times2)

0     2
1     4
2     6
3     8
4    18
5    12
Name: col1, dtype: int64

In [12]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
4    3
5    3
Name: col3, dtype: int64

In [13]:
df['col1'].sum()

np.int64(25)

** Permanently Removing a Column**

In [62]:
del df['col1']

In [63]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

** Get column and index names: **

In [64]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [65]:
df.index

RangeIndex(start=0, stop=4, step=1)

** Sorting and Ordering a DataFrame:**

In [66]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [67]:
df.sort_values(by='col2') #inplace=False by default                


#inplace means original mai changes
# inplace=False → (Default)
# Returns a new DataFrame with changes.
#  Does not modify the original DataFrame.

# inplace=True →
# Changes happen directly in the original DataFrame (no new copy returned).

   col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

** Find Null Values or Check for Null Values**

In [68]:
df.isnull()

    col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [69]:
# Drop rows with NaN Values
df.dropna()

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

** Filling in NaN values with something else: **

In [18]:
import numpy as np

In [19]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [20]:
df.fillna('FILL')

   col1   col2 col3
0   1.0   FILL  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3  FILL  444.0  xyz

In [22]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}
f = pd.DataFrame(data)

In [23]:
df

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [ ]:

# 🧠 What is a Pivot Table?

# A pivot table means:

# “Turn your long data table into a summary table that shows information in a more organized and easy-to-read format.”

# It rearranges your data — just like you do in Excel Pivot Tables.




# | A (Company) | B (Branch) | C (Product) | D (Sales) |
# | ----------- | ---------- | ----------- | --------- |
# | foo         | one        | x           | 1         |
# | foo         | one        | y           | 3         |
# | foo         | two        | x           | 2         |
# | bar         | two        | y           | 5         |
# | bar         | one        | x           | 4         |
# | bar         | one        | y           | 1         |

# 🎯 Goal

# We want to see:

# “For each Company (A) and Branch (B), what are the sales of each Product (C)?”

# So we use:

# df.pivot_table(values='Dx', index=['A','B'], columns='C')


# 🔄 Step-by-Step Visualization
# Step 1 — Take A and B as rows
#     | A   | B   |
# | --- | --- |
# | bar | one |
# | bar | two |
# | foo | one |
# | foo | two |


# Step 2 — Take C as columns

# C has two values → x, y
# | A | B | x | y |
# | - | - | - | - |


# Step 3 — Fill in the D (Sales) values

# Now, fill each cell with the correct sales value from the table:

# | A   | B   | x   | y   |
# | --- | --- | --- | --- |
# | bar | one | 4   | 1   |
# | bar | two | NaN | 5   |
# | foo | one | 1   | 3   |
# | foo | two | 2   | NaN |
# ✅ If a combination doesn’t exist → NaN (missing)


# So this pivot table says:
# | Company | Branch | Product X | Product Y |
# | ------- | ------ | --------- | --------- |
# | bar     | one    | 4         | 1         |
# | bar     | two    | –         | 5         |
# | foo     | one    | 1         | 3         |
# | foo     | two    | 2         | –         |



# 📘 Summary
# Concept	Description
# index	What becomes the rows (like “Company”, “Branch”)
# columns	What becomes the columns (like “Product”)
# values	What fills the cells (like “Sales”)
# aggfunc	How to combine duplicates (default = mean)

In [26]:
df.pivot_table(values=data,index=['A', 'B'],columns=['C'])

KeyError: 'A'

# Great Job!