In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("pn_data.csv")
df

     Name  Age  Monthly_Salary
0     Ram   22           20000
1    Ravi   23           24000
2    John   21           24000
3    Rony   20           23000
4   Rohit   22           21000
5    Sonu   25           34000
6    Neha   23           32000
7  Rupali   22           31000
8  Sanjay   21           28000
9    Monu   19           30000

In [4]:
# select a column
df[["Name"]]

     Name
0     Ram
1    Ravi
2    John
3    Rony
4   Rohit
5    Sonu
6    Neha
7  Rupali
8  Sanjay
9    Monu

In [5]:
# select multiple columns
df[["Name", "Monthly_Salary"]]

     Name  Monthly_Salary
0     Ram           20000
1    Ravi           24000
2    John           24000
3    Rony           23000
4   Rohit           21000
5    Sonu           34000
6    Neha           32000
7  Rupali           31000
8  Sanjay           28000
9    Monu           30000

In [6]:
# select single row
df.loc[df.Name == "Ravi"]

   Name  Age  Monthly_Salary
1  Ravi   23           24000

In [7]:
df.loc[(df.Name == "Ram" ) & (df.Monthly_Salary >= 9000)]

  Name  Age  Monthly_Salary
0  Ram   22           20000

In [8]:
df.loc[0:2]

   Name  Age  Monthly_Salary
0   Ram   22           20000
1  Ravi   23           24000
2  John   21           24000

In [9]:
df.iloc[0:2]

   Name  Age  Monthly_Salary
0   Ram   22           20000
1  Ravi   23           24000

In [10]:
# 5 filter Data Frame
df

     Name  Age  Monthly_Salary
0     Ram   22           20000
1    Ravi   23           24000
2    John   21           24000
3    Rony   20           23000
4   Rohit   22           21000
5    Sonu   25           34000
6    Neha   23           32000
7  Rupali   22           31000
8  Sanjay   21           28000
9    Monu   19           30000

In [11]:
df["Age"] > 21

0     True
1     True
2    False
3    False
4     True
5     True
6     True
7     True
8    False
9    False
Name: Age, dtype: bool

In [12]:
df[df ["Age"]>=21]

     Name  Age  Monthly_Salary
0     Ram   22           20000
1    Ravi   23           24000
2    John   21           24000
4   Rohit   22           21000
5    Sonu   25           34000
6    Neha   23           32000
7  Rupali   22           31000
8  Sanjay   21           28000

In [13]:
df_age_filter = df[df["Age"] >= 22]
df_age_filter

     Name  Age  Monthly_Salary
0     Ram   22           20000
1    Ravi   23           24000
4   Rohit   22           21000
5    Sonu   25           34000
6    Neha   23           32000
7  Rupali   22           31000

In [15]:
df[(df["Age"] >= 22) & (df["Monthly_Salary"] >= 24000)]

     Name  Age  Monthly_Salary
1    Ravi   23           24000
5    Sonu   25           34000
6    Neha   23           32000
7  Rupali   22           31000

In [17]:
df.where(df["Age"] > 22)

   Name   Age  Monthly_Salary
0   NaN   NaN             NaN
1  Ravi  23.0         24000.0
2   NaN   NaN             NaN
3   NaN   NaN             NaN
4   NaN   NaN             NaN
5  Sonu  25.0         34000.0
6  Neha  23.0         32000.0
7   NaN   NaN             NaN
8   NaN   NaN             NaN
9   NaN   NaN             NaN

In [18]:
df[df["Age"] > 22]

   Name  Age  Monthly_Salary
1  Ravi   23           24000
5  Sonu   25           34000
6  Neha   23           32000