In [ ]:
#TOPIC- READING AND WRITING   DATA(TABLE DATA) OF SQL DATABASE (XAMPP) THROUGH PANDAS

In [ ]:
#1.How to read data of table created in database (Xampp)

In [1]:
import numpy as np
import pandas as pd

In [2]:
!pip install sqlalchemy 
# its a library
# ye command SQLAlchemy library install karti hai

# SQLAlchemy Python ka database connectivity & ORM (Object Relational Mapping) tool hai

# Iske through Python se SQL queries run kar sakte hain

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\users\vision\appdata\roaming\python\python312\site-packages (2.0.42)
Requirement already satisfied: greenlet>=1 in c:\users\vision\appdata\roaming\python\python312\site-packages (from sqlalchemy) (3.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\vision\appdata\roaming\python\python312\site-packages (from sqlalchemy) (4.14.1)

In [3]:
from sqlalchemy import create_engine
 # create_engine() functon ka use database connection banane ke liye hota hai
# pymsql is driver which connect to mtsql database

In [9]:
username = 'root'
password = 'swati123'
host = 'localhost'
port = '3306'
database = 'startersql'

In [10]:
pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\vision\appdata\roaming\python\python312\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [11]:
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')
# engine = create_engine("mysql+pymysql://root:@localhost/isha")

In [12]:
query = "SELECT * FROM users"

In [13]:
df = pd.read_sql(query,con=engine)

In [14]:
df

   id   name                           email  gender         dob  salary
0   1  SWATI   SWATI.TIWARI250902@ GMAIL.COM  female  2002-09-25   34000
1   5  SOMYA  SOMYA.TIWARI29092001@GMAIL.COM  female  2001-03-29   80000

In [1]:
# Practice Question "School" database have "student" table

In [2]:
import pandas as pd

In [3]:
from sqlalchemy import create_engine

In [4]:
username = 'root'
password = ''
host = 'localhost'
port = '3306'
database = '  '

In [5]:
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

In [13]:
query = "SELECT * FROM `Students record`"  # the table name is sudent record but in query it should be Student and database name have spaces so i have to close it in backticks

In [14]:
df = pd.read_sql(query,con=engine)
df

  id   name marks
0  0  swati    89
1  1  somya    93

In [15]:

# Q1. Read all records from students tableengine)

In [16]:
df = pd.read_sql("SELECT * FROM `Students record`", engine)
print(df)

  id   name marks
0  0  swati    89
1  1  somya    93

In [17]:
#Q2  Get students who scored more than 80

In [20]:
df = pd.read_sql("SELECT * FROM `Students record` WHERE marks > 80", engine)
print(df)

  id   name marks
0  0  swati    89
1  1  somya    93

In [ ]:
#WRITING DATA IN SQL TABLE THROUGH PANDAS

In [21]:

#.How to write data in database table(which is created in xammp)

In [23]:
import pandas as pd
from sqlalchemy import create_engine

# Connection settings
username = 'root'
password = ''  # Default for XAMPP
host = 'localhost'
port = 3306
database = 'school record'
# Create engine
engine = create_engine(f"mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}")

In [29]:
data = {
    'id':[2,3,4],
    'name': ['Tina', 'Arun', 'Neha'],
    'marks': [87, 91, 76],
    
}

df = pd.DataFrame(data)

In [30]:
df.to_sql(name='students record', con=engine, if_exists='append', index=False)

-1

In [31]:
# PRACTICE QUESTIONS related to writing in database table :

In [32]:
#Q1. Insert one record (manually created DataFrame) into "students" table
#Hint: Use to_sql() with append.

In [33]:
df = pd.DataFrame({'id': ['6'],'name': ['Ravi'], 'marks': [78]})
df.to_sql(name='students record', con=engine, if_exists='append', index=False)

-1

In [34]:
#Q2. Insert multiple records at once

In [36]:
data = {
    'id': ['7', '8', '9'],
    'name': ['Anu', 'Deepa', 'Rakesh'],
    'marks': [77, 69, 88],
    
}
df = pd.DataFrame(data)
df.to_sql('students record', con=engine, if_exists='append', index=False)

-1

In [37]:
#Q3. Replace entire table with new records
#Hint: Use if_exists='replace'

In [14]:
df = pd.DataFrame({
    'id': ['10', '11'],
    'name': ['Kriti', 'Mohit'],
    'marks': [90, 92],
    
})
df.to_sql('students_record', con=engine, if_exists='replace', index=False)

2

In [16]:
#Q4. Insert data and include index column


import pandas as pd
from sqlalchemy import create_engine

# Connection settings
username = 'root'
password = ''  # Default for XAMPP
host = 'localhost'
port = 3306
database = 'data'

# Create engine
engine = create_engine("mysql+pymysql://root:@localhost/data")

df = pd.DataFrame({
    'name': ['Simran', 'Amit'],
    'marks': [73, 85]
})
df.index.name = 'roll_no'
df.to_sql('raghavi', con=engine, if_exists='replace', index=True)

2

In [17]:
#Q5. Read specific columns using SQL
import pandas as pd
from sqlalchemy import create_engine

# Connection settings
username = 'root'
password = ''  # Default for XAMPP
host = 'localhost'
port = 3306
database = 'data'

# Create engine
engine = create_engine("mysql+pymysql://root:@localhost/data") 

data = pd.read_sql('SELECT Name FROM raghavi', con=engine)
print(data)

     Name
0  Simran
1    Amit

In [20]:
#Q6. Use index_label to rename index column in SQL table
import pandas as pd
from sqlalchemy import create_engine

# Connection settings
username = 'root'
password = ''  # Default for XAMPP
host = 'localhost'
port = 3306
database = 'data'

# Create engine
engine = create_engine("mysql+pymysql://root:@localhost/data")
df = pd.DataFrame({
    'name': ['Kiran', 'Alok'],
    'marks': [67, 77]
})
df.to_sql('raghavi', con=engine, if_exists='replace', index=True, index_label='id')

2

In [22]:
# Q7. Write different DataFrames to different tables  (this automatically create tables in data Database
import pandas as pd
from sqlalchemy import create_engine

# Connection settings
username = 'root'
password = ''  # Default for XAMPP
host = 'localhost'
port = 3306
database = 'data'

# Create engine
engine = create_engine("mysql+pymysql://root:@localhost/data")

df1 = pd.DataFrame({'Name': ['Raj'], 'Marks': [91]})
df1.to_sql('s_class', con=engine, if_exists='replace', index=False)

df2 = pd.DataFrame({'Name': ['Neha'], 'Marks': [87]})
df2.to_sql('m_class', con=engine, if_exists='replace', index=False)

1

In [27]:
# Q8. Use condition to filter data in SQL and load into Pandas
import pandas as pd
from sqlalchemy import create_engine
username = 'root'
password = ''  # Default for XAMPP
host = 'localhost'
port = 3306
database = 'data'

# Create engine
engine = create_engine("mysql+pymysql://root:@localhost/data")
query = "SELECT * FROM s_class WHERE Marks > 85"
high_scores = pd.read_sql(query, con=engine)
print(high_scores)

  Name  Marks
0  Raj     91

In [28]:
#Q9. Try inserting empty DataFrame
import pandas as pd
from sqlalchemy import create_engine
username = 'root'
password = ''  # Default for XAMPP
host = 'localhost'
port = 3306
database = 'data'

# Create engine
engine = create_engine("mysql+pymysql://root:@localhost/data")
df_empty = pd.DataFrame(columns=['Name', 'Marks'])
df_empty.to_sql('empty_table', con=engine, if_exists='replace', index=False)

0

In [29]:
#Q10. Insert timestamp column
import pandas as pd
from datetime import datetime
from sqlalchemy import create_engine
username = 'root'
password = ''  # Default for XAMPP
host = 'localhost'
port = 3306
database = 'data'

# Create engine
engine = create_engine("mysql+pymysql://root:@localhost/data")


df = pd.DataFrame({
    'Name': ['Varun'],
    'Marks': [88],
    'Updated': [datetime.now()]
})

df.to_sql('students_time', con=engine, if_exists='append', index=False)

1

In [ ]:
# NOTE: in pandas we can not directly make database in xampp directly but we can make a table in databse directly by pandas