In [25]:
# Data Cleaning Tasks: Handle missing values, remove duplicate records and correct data types.

In [26]:
import pandas as pd

# read data set

In [27]:
df = pd.read_csv("SalesDataset.csv")

In [28]:
df

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
0,1,2025-10-20,Aarav,45.0,Jaipur,Laptop,Electronics,4,30815.0,15,104771.0,Cash,Cancelled
1,2,2025-03-24,Aarav,51.0,Jaipur,Keyboard,Accessories,2,16883.0,10,30389.4,UPI,Processing
2,3,2025-03-13,Ayesha,42.0,Jaipur,Keyboard,Accessories,5,30438.0,5,144580.5,Card,Processing
3,4,2025-12-05,Ayesha,26.0,NaN,Phone,Electronics,8,40694.0,15,276719.2,UPI,Cancelled
4,5,2025-01-03,Kabir,26.0,Mumbai,Keyboard,Accessories,6,51097.0,5,291252.9,Cash,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,351,2025-12-17,Najrin,18.0,Chennai,Keyboard,Accessories,5,42333.0,10,190498.5,Cash,Delivered
1016,587,2025-08-14,Najrin,36.0,Mumbai,Laptop,Electronics,1,10956.0,0,10956.0,Cash,Cancelled
1017,778,2025-12-29,Ayesha,36.0,Chennai,Phone,Electronics,4,32689.0,10,117680.4,Card,Delivered
1018,150,2025-05-05,Diya,45.0,Jaipur,Keyboard,Accessories,4,25447.0,0,101788.0,Card,Processing
1019,537,2025-02-21,Rehan,32.0,Mumbai,Printer,Office,8,36305.0,15,246874.0,Card,Processing

In [29]:
# check missing values
df.isnull()

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,False,False,False,False,False,False,False,False,False,False,False,False,False
1016,False,False,False,False,False,False,False,False,False,False,False,False,False
1017,False,False,False,False,False,False,False,False,False,False,False,False,False
1018,False,False,False,False,False,False,False,False,False,False,False,False,False
1019,False,False,False,False,False,False,False,False,False,False,False,False,False

In [30]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerName     0
Age             61
City            82
Product          0
Category         0
Quantity         0
UnitPrice       41
Discount         0
TotalSales       0
PaymentMode      0
OrderStatus      0
dtype: int64

In [31]:
# remove missing values
df.dropna()

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
0,1,2025-10-20,Aarav,45.0,Jaipur,Laptop,Electronics,4,30815.0,15,104771.0,Cash,Cancelled
1,2,2025-03-24,Aarav,51.0,Jaipur,Keyboard,Accessories,2,16883.0,10,30389.4,UPI,Processing
2,3,2025-03-13,Ayesha,42.0,Jaipur,Keyboard,Accessories,5,30438.0,5,144580.5,Card,Processing
4,5,2025-01-03,Kabir,26.0,Mumbai,Keyboard,Accessories,6,51097.0,5,291252.9,Cash,Cancelled
6,7,2025-05-03,Aarav,20.0,Jaipur,Keyboard,Accessories,2,35462.0,0,70924.0,UPI,Processing
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,351,2025-12-17,Najrin,18.0,Chennai,Keyboard,Accessories,5,42333.0,10,190498.5,Cash,Delivered
1016,587,2025-08-14,Najrin,36.0,Mumbai,Laptop,Electronics,1,10956.0,0,10956.0,Cash,Cancelled
1017,778,2025-12-29,Ayesha,36.0,Chennai,Phone,Electronics,4,32689.0,10,117680.4,Card,Delivered
1018,150,2025-05-05,Diya,45.0,Jaipur,Keyboard,Accessories,4,25447.0,0,101788.0,Card,Processing
1019,537,2025-02-21,Rehan,32.0,Mumbai,Printer,Office,8,36305.0,15,246874.0,Card,Processing

In [32]:
# mean se
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [33]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerName     0
Age              0
City            82
Product          0
Category         0
Quantity         0
UnitPrice       41
Discount         0
TotalSales       0
PaymentMode      0
OrderStatus      0
dtype: int64

In [34]:
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [35]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerName     0
Age              0
City             0
Product          0
Category         0
Quantity         0
UnitPrice       41
Discount         0
TotalSales       0
PaymentMode      0
OrderStatus      0
dtype: int64

In [36]:
df["UnitPrice"] = df["UnitPrice"].fillna(df["UnitPrice"].mean())

In [37]:
df.isnull().sum()

OrderID         0
OrderDate       0
CustomerName    0
Age             0
City            0
Product         0
Category        0
Quantity        0
UnitPrice       0
Discount        0
TotalSales      0
PaymentMode     0
OrderStatus     0
dtype: int64

# Handle duplicate data

In [38]:
# check duplicate data
df.duplicated().sum()

np.int64(20)

In [39]:
df.drop_duplicates(inplace=True)

In [40]:
df.duplicated().sum()

np.int64(0)

# Correct Data Types

In [41]:
df.dtypes

OrderID           int64
OrderDate           str
CustomerName        str
Age             float64
City                str
Product             str
Category            str
Quantity            str
UnitPrice       float64
Discount          int64
TotalSales      float64
PaymentMode         str
OrderStatus         str
dtype: object

In [42]:
df["Age"] = df["Age"].astype(int)

In [43]:
# save Clean dataset 
df.to_excel("Cleaned_Data.xlsx", index=False)