<!-- Data Filtering in Pandas -->

# Data Filtering in Pandas

In [1]:
# Objective

# Create a filtered version of the dataset by:

# Filtering rows
# Selecting columns
# Sorting data

In [2]:
# 1. Import Pandas
import pandas as pd

In [3]:
# 2. Read CSV File
df = pd.read_csv("SalesDataset.csv")

In [4]:
# 3. Display Dataset
df.head()

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
0,1,2025-10-20,Aarav,45.0,Jaipur,Laptop,Electronics,4,30815.0,15,104771.0,Cash,Cancelled
1,2,2025-03-24,Aarav,51.0,Jaipur,Keyboard,Accessories,2,16883.0,10,30389.4,UPI,Processing
2,3,2025-03-13,Ayesha,42.0,Jaipur,Keyboard,Accessories,5,30438.0,5,144580.5,Card,Processing
3,4,2025-12-05,Ayesha,26.0,NaN,Phone,Electronics,8,40694.0,15,276719.2,UPI,Cancelled
4,5,2025-01-03,Kabir,26.0,Mumbai,Keyboard,Accessories,6,51097.0,5,291252.9,Cash,Cancelled

In [5]:
# 4. Select Columns
df["Product"]

0         Laptop
1       Keyboard
2       Keyboard
3          Phone
4       Keyboard
          ...
1015    Keyboard
1016      Laptop
1017       Phone
1018    Keyboard
1019     Printer
Name: Product, Length: 1020, dtype: str

In [6]:
df[["Product", "TotalSales", "City"]]

       Product  TotalSales     City
0       Laptop    104771.0   Jaipur
1     Keyboard     30389.4   Jaipur
2     Keyboard    144580.5   Jaipur
3        Phone    276719.2      NaN
4     Keyboard    291252.9   Mumbai
...        ...         ...      ...
1015  Keyboard    190498.5  Chennai
1016    Laptop     10956.0   Mumbai
1017     Phone    117680.4  Chennai
1018  Keyboard    101788.0   Jaipur
1019   Printer    246874.0   Mumbai

[1020 rows x 3 columns]

In [7]:
# 5. Filter Rows
df[df["TotalSales"] > 10000]

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
0,1,2025-10-20,Aarav,45.0,Jaipur,Laptop,Electronics,4,30815.0,15,104771.0,Cash,Cancelled
1,2,2025-03-24,Aarav,51.0,Jaipur,Keyboard,Accessories,2,16883.0,10,30389.4,UPI,Processing
2,3,2025-03-13,Ayesha,42.0,Jaipur,Keyboard,Accessories,5,30438.0,5,144580.5,Card,Processing
3,4,2025-12-05,Ayesha,26.0,NaN,Phone,Electronics,8,40694.0,15,276719.2,UPI,Cancelled
4,5,2025-01-03,Kabir,26.0,Mumbai,Keyboard,Accessories,6,51097.0,5,291252.9,Cash,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,351,2025-12-17,Najrin,18.0,Chennai,Keyboard,Accessories,5,42333.0,10,190498.5,Cash,Delivered
1016,587,2025-08-14,Najrin,36.0,Mumbai,Laptop,Electronics,1,10956.0,0,10956.0,Cash,Cancelled
1017,778,2025-12-29,Ayesha,36.0,Chennai,Phone,Electronics,4,32689.0,10,117680.4,Card,Delivered
1018,150,2025-05-05,Diya,45.0,Jaipur,Keyboard,Accessories,4,25447.0,0,101788.0,Card,Processing
1019,537,2025-02-21,Rehan,32.0,Mumbai,Printer,Office,8,36305.0,15,246874.0,Card,Processing

In [8]:
# Only Delhi records
df[df["City"] == "Delhi"]

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
14,15,2025-02-20,Rehan,20.0,Delhi,Printer,Office,2,3814.0,10,6865.20,UPI,Delivered
17,18,2025-11-26,Zoya,19.0,Delhi,Keyboard,Accessories,7,56285.0,5,374295.25,Card,Processing
22,23,2025-04-13,Diya,NaN,Delhi,Laptop,Electronics,6,17191.0,10,92831.40,Cash,Processing
31,32,2025-11-07,Ayesha,28.0,Delhi,Keyboard,Accessories,2,26544.0,15,45124.80,Card,Processing
47,48,2025-08-22,Ayesha,29.0,Delhi,Printer,Office,8,32535.0,10,234252.00,Card,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,983,2025-03-16,Aarav,53.0,Delhi,Phone,Electronics,3,42154.0,0,126462.00,Cash,Processing
985,986,2025-11-17,Diya,NaN,Delhi,Laptop,Electronics,2,55377.0,10,99678.60,Cash,Delivered
1004,657,2025-03-07,Diya,50.0,Delhi,Laptop,Electronics,1,28143.0,0,28143.00,Cash,Cancelled
1005,320,2025-07-04,Rehan,42.0,Delhi,Printer,Office,4,1873.0,5,7117.40,UPI,Delivered
1007,493,2025-06-25,Najrin,34.0,Delhi,Keyboard,Accessories,6,31110.0,5,177327.00,Card,Cancelled

In [9]:
# Shoes category
df[df["Category"] == "Office"]

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
12,13,2025-09-26,Najrin,NaN,Jaipur,Printer,Office,2,11399.0,15,19378.3,Card,Processing
14,15,2025-02-20,Rehan,20.0,Delhi,Printer,Office,2,3814.0,10,6865.2,UPI,Delivered
15,16,2025-02-25,Zoya,NaN,Mumbai,Printer,Office,7,51264.0,15,305020.8,Cash,Cancelled
20,21,2025-02-19,Najrin,47.0,Pune,Printer,Office,8,NaN,5,334552.0,Cash,Cancelled
32,33,2025-01-31,Riya,46.0,Pune,Printer,Office,8,47853.0,15,325400.4,Card,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,320,2025-07-04,Rehan,42.0,Delhi,Printer,Office,4,1873.0,5,7117.4,UPI,Delivered
1008,791,2025-02-20,Najrin,30.0,Jaipur,Printer,Office,4,18730.0,5,71174.0,Cash,Cancelled
1012,21,2025-02-19,Najrin,47.0,Pune,Printer,Office,8,NaN,5,334552.0,Cash,Cancelled
1014,557,2025-07-20,Najrin,NaN,Pune,Printer,Office,2,21733.0,0,43466.0,Cash,Processing
1019,537,2025-02-21,Rehan,32.0,Mumbai,Printer,Office,8,36305.0,15,246874.0,Card,Processing

In [10]:
# Quantity greater than 5
df[df["Discount"] > 10]

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
0,1,2025-10-20,Aarav,45.0,Jaipur,Laptop,Electronics,4,30815.0,15,104771.0,Cash,Cancelled
3,4,2025-12-05,Ayesha,26.0,NaN,Phone,Electronics,8,40694.0,15,276719.2,UPI,Cancelled
11,12,2025-05-15,Zoya,NaN,Chennai,Phone,Electronics,7,57486.0,15,342041.7,Card,Delivered
12,13,2025-09-26,Najrin,NaN,Jaipur,Printer,Office,2,11399.0,15,19378.3,Card,Processing
15,16,2025-02-25,Zoya,NaN,Mumbai,Printer,Office,7,51264.0,15,305020.8,Cash,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,970,2025-12-24,Ayesha,46.0,NaN,Keyboard,Accessories,6,13089.0,15,66753.9,UPI,Cancelled
970,971,2025-08-01,Riya,55.0,Jaipur,Printer,Office,five,9678.0,15,8226.3,UPI,Delivered
980,981,2025-08-24,Rehan,58.0,Jaipur,Phone,Electronics,2,13614.0,15,23143.8,Cash,Delivered
1011,970,2025-12-24,Ayesha,46.0,NaN,Keyboard,Accessories,6,13089.0,15,66753.9,UPI,Cancelled
1019,537,2025-02-21,Rehan,32.0,Mumbai,Printer,Office,8,36305.0,15,246874.0,Card,Processing

In [11]:
# 6. Multiple Conditions
df[(df["City"] == "Delhi") & (df["TotalSales"] > 10000)]

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
17,18,2025-11-26,Zoya,19.0,Delhi,Keyboard,Accessories,7,56285.0,5,374295.25,Card,Processing
22,23,2025-04-13,Diya,NaN,Delhi,Laptop,Electronics,6,17191.0,10,92831.40,Cash,Processing
31,32,2025-11-07,Ayesha,28.0,Delhi,Keyboard,Accessories,2,26544.0,15,45124.80,Card,Processing
47,48,2025-08-22,Ayesha,29.0,Delhi,Printer,Office,8,32535.0,10,234252.00,Card,Delivered
49,50,2025-09-26,Najrin,27.0,Delhi,Laptop,Electronics,5,46728.0,10,210276.00,UPI,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,982,2025-07-09,Zoya,48.0,Delhi,Printer,Office,8,32165.0,0,257320.00,Cash,Cancelled
982,983,2025-03-16,Aarav,53.0,Delhi,Phone,Electronics,3,42154.0,0,126462.00,Cash,Processing
985,986,2025-11-17,Diya,NaN,Delhi,Laptop,Electronics,2,55377.0,10,99678.60,Cash,Delivered
1004,657,2025-03-07,Diya,50.0,Delhi,Laptop,Electronics,1,28143.0,0,28143.00,Cash,Cancelled
1007,493,2025-06-25,Najrin,34.0,Delhi,Keyboard,Accessories,6,31110.0,5,177327.00,Card,Cancelled

In [12]:
# Mumbai OR Jeans
df[(df["City"] == "Mumbai") | (df["Category"] == "Jeans")]

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
4,5,2025-01-03,Kabir,26.0,Mumbai,Keyboard,Accessories,6,51097.0,5,291252.9,Cash,Cancelled
7,8,2025-10-18,Ayesha,56.0,Mumbai,Laptop,Electronics,2,29437.0,5,55930.3,UPI,Processing
8,9,2025-08-10,Rehan,46.0,Mumbai,Keyboard,Accessories,3,40952.0,5,116713.2,UPI,Processing
15,16,2025-02-25,Zoya,NaN,Mumbai,Printer,Office,7,51264.0,15,305020.8,Cash,Cancelled
37,38,2025-04-10,Zoya,28.0,Mumbai,Printer,Office,8,51442.0,10,370382.4,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,999,2025-09-16,Riya,40.0,Mumbai,Keyboard,Accessories,5,45853.0,10,206338.5,UPI,Processing
1000,432,2025-09-20,Riya,35.0,Mumbai,Phone,Electronics,8,7391.0,0,59128.0,Cash,Delivered
1006,614,2025-03-04,Rehan,46.0,Mumbai,Laptop,Electronics,3,4008.0,10,10821.6,Cash,Delivered
1016,587,2025-08-14,Najrin,36.0,Mumbai,Laptop,Electronics,1,10956.0,0,10956.0,Cash,Cancelled
1019,537,2025-02-21,Rehan,32.0,Mumbai,Printer,Office,8,36305.0,15,246874.0,Card,Processing

In [13]:
# 7. isin()
df[df["City"].isin(["Delhi", "Mumbai"])]

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
4,5,2025-01-03,Kabir,26.0,Mumbai,Keyboard,Accessories,6,51097.0,5,291252.9,Cash,Cancelled
7,8,2025-10-18,Ayesha,56.0,Mumbai,Laptop,Electronics,2,29437.0,5,55930.3,UPI,Processing
8,9,2025-08-10,Rehan,46.0,Mumbai,Keyboard,Accessories,3,40952.0,5,116713.2,UPI,Processing
14,15,2025-02-20,Rehan,20.0,Delhi,Printer,Office,2,3814.0,10,6865.2,UPI,Delivered
15,16,2025-02-25,Zoya,NaN,Mumbai,Printer,Office,7,51264.0,15,305020.8,Cash,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,320,2025-07-04,Rehan,42.0,Delhi,Printer,Office,4,1873.0,5,7117.4,UPI,Delivered
1006,614,2025-03-04,Rehan,46.0,Mumbai,Laptop,Electronics,3,4008.0,10,10821.6,Cash,Delivered
1007,493,2025-06-25,Najrin,34.0,Delhi,Keyboard,Accessories,6,31110.0,5,177327.0,Card,Cancelled
1016,587,2025-08-14,Najrin,36.0,Mumbai,Laptop,Electronics,1,10956.0,0,10956.0,Cash,Cancelled
1019,537,2025-02-21,Rehan,32.0,Mumbai,Printer,Office,8,36305.0,15,246874.0,Card,Processing

In [14]:
# 8. Between()
df[df["TotalSales"].between(5000,15000)]

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
14,15,2025-02-20,Rehan,20.0,Delhi,Printer,Office,2,3814.0,10,6865.2,UPI,Delivered
44,45,2025-04-14,Kabir,33.0,Jaipur,printer,Office,1,8714.0,0,8714.0,UPI,Delivered
48,49,2025-03-13,Najrin,34.0,Mumbai,Laptop,Electronics,8,1371.0,5,10419.6,Cash,Delivered
70,71,2025-11-05,Riya,51.0,Delhi,Laptop,Electronics,1,NaN,15,9586.3,Cash,Delivered
92,93,2025-04-07,Riya,NaN,Delhi,Phone,Electronics,3,4463.0,10,12050.1,Cash,Processing
...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,971,2025-08-01,Riya,55.0,Jaipur,Printer,Office,five,9678.0,15,8226.3,UPI,Delivered
1005,320,2025-07-04,Rehan,42.0,Delhi,Printer,Office,4,1873.0,5,7117.4,UPI,Delivered
1006,614,2025-03-04,Rehan,46.0,Mumbai,Laptop,Electronics,3,4008.0,10,10821.6,Cash,Delivered
1010,276,2025-10-29,Ayesha,19.0,Jaipur,Laptop,Electronics,8,1332.0,10,9590.4,Cash,Processing
1016,587,2025-08-14,Najrin,36.0,Mumbai,Laptop,Electronics,1,10956.0,0,10956.0,Cash,Cancelled

In [15]:
# 9. String Filtering
# Starts with A
df[df["CustomerName"].str.startswith("A")]

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
0,1,2025-10-20,Aarav,45.0,Jaipur,Laptop,Electronics,4,30815.0,15,104771.0,Cash,Cancelled
2,3,2025-03-13,Ayesha,42.0,Jaipur,Keyboard,Accessories,5,30438.0,5,144580.5,Card,Processing
3,4,2025-12-05,Ayesha,26.0,NaN,Phone,Electronics,8,40694.0,15,276719.2,UPI,Cancelled
6,7,2025-05-03,Aarav,20.0,Jaipur,Keyboard,Accessories,2,35462.0,0,70924.0,UPI,Processing
7,8,2025-10-18,Ayesha,56.0,Mumbai,Laptop,Electronics,2,29437.0,5,55930.3,UPI,Processing
...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,993,2025-04-19,Aarav,55.0,Jaipur,Laptop,Electronics,7,38951.0,10,245391.3,Cash,Cancelled
1010,276,2025-10-29,Ayesha,19.0,Jaipur,Laptop,Electronics,8,1332.0,10,9590.4,Cash,Processing
1011,970,2025-12-24,Ayesha,46.0,NaN,Keyboard,Accessories,6,13089.0,15,66753.9,UPI,Cancelled
1013,469,2025-08-10,Aarav,48.0,Bhopal,Keyboard,Accessories,3,29212.0,5,83254.2,UPI,Processing
1017,778,2025-12-29,Ayesha,36.0,Chennai,Phone,Electronics,4,32689.0,10,117680.4,Card,Delivered

In [16]:
# Contains "phone"
df[df["Product"].str.contains("phone", case=False)]

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
3,4,2025-12-05,Ayesha,26.0,NaN,Phone,Electronics,8,40694.0,15,276719.2,UPI,Cancelled
9,10,2025-08-22,Najrin,28.0,Pune,Phone,Electronics,3,31966.0,10,86308.2,Cash,Processing
11,12,2025-05-15,Zoya,NaN,Chennai,Phone,Electronics,7,57486.0,15,342041.7,Card,Delivered
16,17,2025-05-13,Zoya,45.0,Bhopal,Phone,Electronics,4,21672.0,0,86688.0,Card,Delivered
19,20,2025-11-01,Rehan,30.0,Bhopal,Phone,Electronics,2,39262.0,5,74597.8,Cash,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,432,2025-09-20,Riya,35.0,Mumbai,Phone,Electronics,8,7391.0,0,59128.0,Cash,Delivered
1001,180,2025-02-26,Zoya,25.0,Pune,Phone,Electronics,6,15001.0,0,90006.0,Card,Cancelled
1003,248,2025-04-18,Riya,33.0,NaN,Phone,Electronics,2,29438.0,10,52988.4,Cash,Cancelled
1009,869,2025-06-15,Diya,60.0,Pune,Phone,Electronics,1,2576.0,10,2318.4,Card,Cancelled
1017,778,2025-12-29,Ayesha,36.0,Chennai,Phone,Electronics,4,32689.0,10,117680.4,Card,Delivered

In [17]:
# 10. Sort Values
# Sales ascending
df.sort_values("TotalSales")

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
799,800,2025-09-25,Aarav,47.0,Delhi,Printer,Office,1,608.0,5,577.6,UPI,Cancelled
240,241,2025-03-06,Diya,46.0,Bhopal,Keyboard,Accessories,2,529.0,15,899.3,Cash,Cancelled
424,425,2025-10-23,Rehan,34.0,Delhi,Phone,Electronics,3,562.0,10,1517.4,Cash,Cancelled
854,855,2025-07-12,Aarav,31.0,Mumbai,Keyboard,Accessories,2,967.0,15,1643.9,Card,Cancelled
566,567,2025-09-10,Rehan,50.0,Chennai,Printer,Office,2,1028.0,15,1747.6,Cash,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,338,2025-06-30,Najrin,23.0,Pune,Printer,Office,8,59074.0,5,448962.4,Card,Delivered
711,712,2025-01-20,Riya,50.0,Jaipur,Phone,Electronics,8,59188.0,5,449828.8,Cash,Processing
309,310,2025-04-11,Riya,19.0,Pune,Phone,Electronics,8,57333.0,0,458664.0,Cash,Cancelled
646,647,2025-01-14,Zoya,27.0,Jaipur,Phone,Electronics,8,57601.0,0,460808.0,Card,Delivered
388,389,2025-04-11,Ayesha,52.0,Mumbai,Phone,Electronics,8,59017.0,0,472136.0,Cash,Delivered

In [18]:
# Sales descending
df.sort_values("TotalSales", ascending=False)

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
388,389,2025-04-11,Ayesha,52.0,Mumbai,Phone,Electronics,8,59017.0,0,472136.0,Cash,Delivered
646,647,2025-01-14,Zoya,27.0,Jaipur,Phone,Electronics,8,57601.0,0,460808.0,Card,Delivered
309,310,2025-04-11,Riya,19.0,Pune,Phone,Electronics,8,57333.0,0,458664.0,Cash,Cancelled
711,712,2025-01-20,Riya,50.0,Jaipur,Phone,Electronics,8,59188.0,5,449828.8,Cash,Processing
337,338,2025-06-30,Najrin,23.0,Pune,Printer,Office,8,59074.0,5,448962.4,Card,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,567,2025-09-10,Rehan,50.0,Chennai,Printer,Office,2,1028.0,15,1747.6,Cash,Cancelled
854,855,2025-07-12,Aarav,31.0,Mumbai,Keyboard,Accessories,2,967.0,15,1643.9,Card,Cancelled
424,425,2025-10-23,Rehan,34.0,Delhi,Phone,Electronics,3,562.0,10,1517.4,Cash,Cancelled
240,241,2025-03-06,Diya,46.0,Bhopal,Keyboard,Accessories,2,529.0,15,899.3,Cash,Cancelled
799,800,2025-09-25,Aarav,47.0,Delhi,Printer,Office,1,608.0,5,577.6,UPI,Cancelled

In [19]:
# Multiple columns
df.sort_values(["City","TotalSales"], ascending=[True,False])

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
259,260,2025-01-04,Najrin,23.0,Bhopal,Laptop,Electronics,8,51534.0,0,412272.0,Card,Delivered
193,194,2025-07-02,Zoya,21.0,Bhopal,Laptop,Electronics,7,58234.0,0,407638.0,Cash,Cancelled
295,296,2025-01-17,Zoya,59.0,Bhopal,keyboard,Accessories,8,56179.0,10,404488.8,Cash,Processing
489,490,2025-06-29,Rehan,26.0,Bhopal,Printer,Office,7,59760.0,5,397404.0,UPI,Cancelled
780,781,2025-03-05,Kabir,40.0,Bhopal,Keyboard,Accessories,7,55787.0,0,390509.0,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,390,2025-08-23,Aarav,29.0,NaN,Laptop,Electronics,1,10184.0,10,9165.6,Card,Processing
939,940,2025-10-06,Aarav,45.0,NaN,Keyboard,Accessories,2,4689.0,5,8909.1,Card,Processing
642,643,2025-05-21,Kabir,23.0,NaN,Keyboard,Accessories,2,3558.0,5,6760.2,Card,Cancelled
194,195,2025-04-30,Zoya,30.0,NaN,Phone,Electronics,3,1407.0,10,3798.9,Card,Delivered
748,749,2025-03-28,Ayesha,42.0,NaN,Phone,Electronics,1,3301.0,10,2970.9,Card,Cancelled

In [20]:
# Largest Sales
# Top 10 sales
df.nlargest(10,"TotalSales")

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
388,389,2025-04-11,Ayesha,52.0,Mumbai,Phone,Electronics,8,59017.0,0,472136.0,Cash,Delivered
646,647,2025-01-14,Zoya,27.0,Jaipur,Phone,Electronics,8,57601.0,0,460808.0,Card,Delivered
309,310,2025-04-11,Riya,19.0,Pune,Phone,Electronics,8,57333.0,0,458664.0,Cash,Cancelled
711,712,2025-01-20,Riya,50.0,Jaipur,Phone,Electronics,8,59188.0,5,449828.8,Cash,Processing
337,338,2025-06-30,Najrin,23.0,Pune,Printer,Office,8,59074.0,5,448962.4,Card,Delivered
778,779,2025-12-26,Zoya,34.0,Jaipur,Laptop,Electronics,8,55281.0,0,442248.0,UPI,Processing
166,167,2025-02-25,Zoya,29.0,Chennai,Laptop,Electronics,8,54984.0,0,439872.0,UPI,Delivered
686,687,2025-10-04,Kabir,55.0,Jaipur,Printer,Office,8,54029.0,0,432232.0,Card,Cancelled
448,449,2025-04-04,Aarav,35.0,Pune,Keyboard,Accessories,8,59745.0,10,430164.0,Card,Processing
253,254,2025-06-27,Ayesha,35.0,Mumbai,Phone,Electronics,8,59375.0,10,427500.0,Card,Cancelled

In [21]:
# Lowest 10 sales
df.nsmallest(10,"TotalSales")

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
799,800,2025-09-25,Aarav,47.0,Delhi,Printer,Office,1,608.0,5,577.60,UPI,Cancelled
240,241,2025-03-06,Diya,46.0,Bhopal,Keyboard,Accessories,2,529.0,15,899.30,Cash,Cancelled
424,425,2025-10-23,Rehan,34.0,Delhi,Phone,Electronics,3,562.0,10,1517.40,Cash,Cancelled
854,855,2025-07-12,Aarav,31.0,Mumbai,Keyboard,Accessories,2,967.0,15,1643.90,Card,Cancelled
566,567,2025-09-10,Rehan,50.0,Chennai,Printer,Office,2,1028.0,15,1747.60,Cash,Cancelled
868,869,2025-06-15,Diya,60.0,Pune,Phone,Electronics,1,2576.0,10,2318.40,Card,Cancelled
1009,869,2025-06-15,Diya,60.0,Pune,Phone,Electronics,1,2576.0,10,2318.40,Card,Cancelled
102,103,2025-07-12,Aarav,48.0,Jaipur,Printer,Office,1,2497.0,5,2372.15,Card,Processing
45,46,2025-01-29,Riya,25.0,Pune,Printer,Office,2,1458.0,15,2478.60,Card,Cancelled
483,484,2025-09-24,Kabir,20.0,Delhi,Keyboard,Accessories,4,685.0,5,2603.00,Cash,Processing

In [ ]:
# Save Filtered Dataset
filtered = df[df["TotalSales"] > 10000]

filtered.to_csv("Filtered_Data.csv", index=False)